# 01A Retrieve EUR-Lex Documents

This workbook reconstructs the main EUR-Lex retrieval layer around the original WebService method used in `NID_Retrieval_Pipeline_EURLEX.ipynb`.

The notebook is intentionally workbook-style: you can edit query terms and retrieval parameters directly here, inspect intermediate job tables and raw rows, inspect one real SOAP response, and then run the full retrieval with explicit fallback only at the nearest retrieval-output level.

# Setup

## Editable parameters in this notebook

Primary edit points:
- primary EUR-Lex search terms
- translated terms
- whether to include translated jobs and NIM scope
- fields searched in the WebService query (`TI`, `TE`)
- chunk size, page size, max pages
- whether to attempt live SOAP/WebService retrieval
- whether to run the parser debug probe and save raw XML
- whether to attempt live batch full-text retrieval
- full-text rate limits, retry counts, and cache usage

In [20]:
from __future__ import annotations

from pathlib import Path
import sys
import os
import importlib

import pandas as pd
from IPython.display import display

ROOT = Path.cwd()
while not (ROOT / "docs_df_cleaned").exists() and ROOT != ROOT.parent:
    ROOT = ROOT.parent
sys.path.insert(0, str(ROOT))

PIPE_DIR = ROOT / "analysis_pipeline"
PIPE_OUT = PIPE_DIR / "outputs"
PIPE_OUT.mkdir(parents=True, exist_ok=True)

pd.set_option("display.max_colwidth", 220)
pd.set_option("display.max_columns", 60)
SAVE_OUTPUTS = True


def preview_df(name: str, df: pd.DataFrame, n: int = 5) -> None:
    print(f"{name}: shape={df.shape}")
    display(df.head(n))


def write_csv(df: pd.DataFrame, path: Path, index: bool = False) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if SAVE_OUTPUTS:
        df.to_csv(path, index=index)
    print(f"{'Wrote' if SAVE_OUTPUTS else 'Would write'}: {path}")
    print(f"Shape: {df.shape}")
    display(df.head())


import analysis_pipeline.functions.eurlex_retrieval as eurlex_retrieval_module
import analysis_pipeline.functions.retrieval_queries as retrieval_queries_module
importlib.reload(eurlex_retrieval_module)
importlib.reload(retrieval_queries_module)

from analysis_pipeline.functions.retrieval_queries import (
    SEARCH_TERMS_PRIMARY,
    TRANSLATED_TERMS_PRIMARY,
)
from analysis_pipeline.functions.eurlex_retrieval import (
    build_eurlex_jobs,
    build_job_chunks,
    build_expert_query,
    build_soap_envelope,
    post_eurlex_ws,
    parse_searchresults,
    build_result_diagnostics,
    extract_result_snippets,
    run_eurlex_jobs,
    load_cached_eu_rows,
    reconstruct_eu_rows_from_corpus,
    build_eu_doc_tables,
    lang_candidates_from_row,
    celex_variants,
    cellar_celex_url,
    annotate_celex_types,
    filter_celex_types_for_fulltext,
    batch_fetch_eurlex_fulltext,
    summarize_fulltext_cache_state,
    load_failed_fulltext_attempts,
    fulltext_cache_validation_diagnostics,
    load_eu_fulltext_docs,
    trace_eurlex_fulltext_decision,
)

CANONICAL_ALL_DOCS = ROOT / "docs_df_cleaned" / "all_docs_df.csv"
CACHED_ROWS = PIPE_OUT / "01A_all_eu_rows.csv"
OUT_FULLTEXT = PIPE_OUT / "01A_eu_all_fulltext_docs_new.csv"
DEBUG_XML_PATH = PIPE_OUT / "page1_raw_response.xml"
FULLTEXT_CACHE_DIR = PIPE_OUT / "eurlex_all_fulltext_cache"
FULLTEXT_INDEX_OUT = PIPE_OUT / "eurlex_all_fulltext_index.csv"
# CACHED_ROWS = PIPE_OUT / "01A_all_eu_en_rows.csv"
# OUT_FULLTEXT = PIPE_OUT / "01A_eu_en_fulltext_docs.csv"
# DEBUG_XML_PATH = PIPE_OUT / "page1_raw_response.xml"
# FULLTEXT_CACHE_DIR = PIPE_OUT / "eurlex_en_fulltext_cache"
# FULLTEXT_INDEX_OUT = PIPE_OUT / "eurlex_en_fulltext_index.csv"

# OUT_ROWS = PIPE_OUT / "01A_all_eu_rows.csv"
# OUT_RAW = PIPE_OUT / "01A_eu_all_df_raw.csv"
# OUT_DOCS = PIPE_OUT / "01A_eu_all_df_docs.csv"

os.environ["EURLEX_USER"] = "n00esrcw"
os.environ["EURLEX_WEB_PASS"] = "FPfgrb83td0"

## Query terms used in this notebook

These cells surface the original primary EUR-Lex retrieval vocabulary directly in the notebook.

Note: the original primary WebService term list did **not** include `net-gain` / `net gain`. Those belonged to the later full-text/body matching layer and remain separate.

In [8]:
SEARCH_TERMS = list(SEARCH_TERMS_PRIMARY)
TRANSLATED_TERMS = {lang: list(terms) for lang, terms in TRANSLATED_TERMS_PRIMARY.items()}

INCLUDE_TRANSLATIONS = True
INCLUDE_NIM_SCOPE = True
FIELDS = ("TI", "TE")
TERMS_PER_QUERY = 12
PAGE_SIZE = 100
PAGE_SIZE_CANDIDATES = (100, 50, 25)
MAX_PAGES = 100
MIN_INTERVAL_S = 1.6
TIMEOUT_S = 45
RETRY_5XX = 3
RUN_LIVE = True
ALLOW_FALLBACK = False
RUN_PARSER_DEBUG_PROBE = True
DEBUG_PAGE_SIZE = 10
DEBUG_TERM_LIMIT = 3
RUN_LIVE_FULLTEXT = True
FULLTEXT_MAX_DOCS = None
FULLTEXT_CELEX_FILTER_MODE = "all"  # all | supported_only | sector_3_only | sector_0_and_3
FULLTEXT_EXCLUDE_DESCRIPTORS = []
FULLTEXT_MIN_INTERVAL_S = 2.0
FULLTEXT_TIMEOUT_S = 45
FULLTEXT_RETRIES = 4
FULLTEXT_USE_CACHE = False
FULLTEXT_VERBOSE = True
FULLTEXT_TRACE_ROUTES = False
FULLTEXT_RESUME = True
FULLTEXT_RETRY_FAILURES = True
FULLTEXT_PROGRESS_EVERY = 5
FULLTEXT_CACHE_EVERY = 50
FULLTEXT_SUCCESS_MIN_CHARS = 500
FALLBACK_FILL_MISSING_TEXT = False
DEBUG = True

os.environ["EURLEX_USER"] = "n00esrcw"
os.environ["EURLEX_WEB_PASS"] = "FPfgrb83td0"

print("Primary search terms")
display(pd.DataFrame({"term": SEARCH_TERMS}))
print("Translated terms preview")
display(
    pd.DataFrame(
        [(lang, term) for lang, terms in TRANSLATED_TERMS.items() for term in terms],
        columns=["language", "term"],
    ).head(25)
)

FULLTEXT_TRACE_SINGLE_TIMEOUT_S = 25

FULLTEXT_TRACE_CELEX_LIST = ["01996L0061", "02002D0272", "02003L0087"]
FULLTEXT_TRACE_SINGLE_TIMEOUT_S = 25

Primary search terms

                       term
0           nature-positive
1           nature positive
2          nature inclusive
3          nature-inclusive
4          nature-inclusive
5   nature inclusive design
6    nature based solutions
7    nature-based solutions
8     biodiversity net gain
9     biodiversity net-gain
10        biodiversity gain
11       nature restoration
12            nature repair
13    biodiversity strategy

Translated terms preview

   language                                            term
0        bg                   интегриран с природата дизайн
1        bg                         природосъобразен дизайн
2        bg                                природопозитивен
3        bg                        природосъобразни решения
4        bg          стратегия за биологичното разнообразие
5        bg    стратегия на ЕС за биологичното разнообразие
6        bg                     възстановяване на природата
7        bg                  възстановяване на екосистемите
8        cs                        návrh zahrnující přírodu
9        cs                           pozitivní pro přírodu
10       cs                      řešení založená na přírodě
11       cs     strategie v oblasti biologické rozmanitosti
12       cs  strategie EU v oblasti biologické rozmanitosti
13       cs                                  obnova přírody
14       cs                               obnova ekosystémů
15       da                               naturinkluderende
16       da                        naturinkluderende design
17       da                                    naturpositiv
18       da                         naturbaserede løsninger
19       da                          biodiversitetsstrategi
20       da                     EU's biodiversitetsstrategi
21       da                           genopretning af natur
22       da                   genopretning af biodiversitet
23       de                       naturverträgliche Planung
24       de                                    naturpositiv

# Query EU docs based on search terms

## Build EUR-Lex jobs

In [3]:
jobs = build_eurlex_jobs(include_translations=INCLUDE_TRANSLATIONS, include_nim=INCLUDE_NIM_SCOPE)

if not INCLUDE_TRANSLATIONS:
    for job in jobs:
        if job["lang"] != "en":
            job["terms"] = []

for job in jobs:
    if job["lang"] == "en":
        job["terms"] = list(SEARCH_TERMS)
    elif INCLUDE_TRANSLATIONS:
        job["terms"] = list(TRANSLATED_TERMS.get(job["lang"], []))

query_jobs = pd.DataFrame(jobs)
query_jobs["term_count"] = query_jobs["terms"].map(len)
preview_df("query_jobs", query_jobs, n=10)
display(query_jobs[["scope", "lang", "expert_scope", "term_count"]].head(20))

query_jobs: shape=(50, 5)

,scope,expert_scope,lang,terms,term_count
0,ALL_ALL,DTS_SUBDOM = ALL_ALL,en,"[nature-positive, nature positive, nature inclusive, nature-inclusive, nature-inclusive, nature inclusive design, nature based solutions, nature-based solutions, biodiversity net gain, biodiversity net-gain, biodiver...",14
1,ALL_ALL,DTS_SUBDOM = ALL_ALL,bg,"[интегриран с природата дизайн, природосъобразен дизайн, природопозитивен, природосъобразни решения, стратегия за биологичното разнообразие, стратегия на ЕС за биологичното разнообразие, възстановяване на природата, ...",8
2,ALL_ALL,DTS_SUBDOM = ALL_ALL,cs,"[návrh zahrnující přírodu, pozitivní pro přírodu, řešení založená na přírodě, strategie v oblasti biologické rozmanitosti, strategie EU v oblasti biologické rozmanitosti, obnova přírody, obnova ekosystémů]",7
3,ALL_ALL,DTS_SUBDOM = ALL_ALL,da,"[naturinkluderende, naturinkluderende design, naturpositiv, naturbaserede løsninger, biodiversitetsstrategi, EU's biodiversitetsstrategi, genopretning af natur, genopretning af biodiversitet]",8
4,ALL_ALL,DTS_SUBDOM = ALL_ALL,de,"[naturverträgliche Planung, naturpositiv, naturbasierte Lösungen, naturbasierte Lösung, Netto-Gewinn, Netto-Gewinn für die Biodiversität, Biodiversitätsstrategie, EU-Biodiversitätsstrategie, Wiederherstellung der Nat...",10
5,ALL_ALL,DTS_SUBDOM = ALL_ALL,el,"[φιλικός προς τη φύση σχεδιασμός, θετικός για τη φύση, λύσεις βασισμένες στη φύση, καθαρό περιβαλλοντικό κέρδος, καθαρό κέρδος για τη βιοποικιλότητα, στρατηγική για τη βιοποικιλότητα, στρατηγική της ΕΕ για τη βιοποικ...",9
6,ALL_ALL,DTS_SUBDOM = ALL_ALL,es,"[diseño respetuoso con la naturaleza, positivo para la naturaleza, soluciones basadas en la naturaleza, ganancia neta, ganancia neta en biodiversidad, ganancia neta para la biodiversidad, estrategia de biodiversidad,...",11
7,ALL_ALL,DTS_SUBDOM = ALL_ALL,et,"[loodusega arvestav disain, looduspositiivne, looduspõhised lahendused, looduspõhine lahendus, elurikkuse strateegia, ELi elurikkuse strateegia, looduse taastamine, ökosüsteemide taastamine]",8
8,ALL_ALL,DTS_SUBDOM = ALL_ALL,fi,"[luontoystävällinen suunnittelu, luontopositiivinen, luontoon perustuvat ratkaisut, luontopohjaiset ratkaisut, biodiversiteettistrategia, EU:n biodiversiteettistrategia, luonnon ennallistaminen, ekosysteemien ennalli...",8
9,ALL_ALL,DTS_SUBDOM = ALL_ALL,fr,"[aménagement respectueux de la nature, positif pour la nature, solutions fondées sur la nature, solution fondée sur la nature, gain net, gain net pour la biodiversité, stratégie pour la biodiversité, stratégie de l'U...",10

      scope lang          expert_scope  term_count
0   ALL_ALL   en  DTS_SUBDOM = ALL_ALL          14
1   ALL_ALL   bg  DTS_SUBDOM = ALL_ALL           8
2   ALL_ALL   cs  DTS_SUBDOM = ALL_ALL           7
3   ALL_ALL   da  DTS_SUBDOM = ALL_ALL           8
4   ALL_ALL   de  DTS_SUBDOM = ALL_ALL          10
5   ALL_ALL   el  DTS_SUBDOM = ALL_ALL           9
6   ALL_ALL   es  DTS_SUBDOM = ALL_ALL          11
7   ALL_ALL   et  DTS_SUBDOM = ALL_ALL           8
8   ALL_ALL   fi  DTS_SUBDOM = ALL_ALL           8
9   ALL_ALL   fr  DTS_SUBDOM = ALL_ALL          10
10  ALL_ALL   hr  DTS_SUBDOM = ALL_ALL          10
11  ALL_ALL   hu  DTS_SUBDOM = ALL_ALL           9
12  ALL_ALL   ga  DTS_SUBDOM = ALL_ALL          10
13  ALL_ALL   it  DTS_SUBDOM = ALL_ALL          11
14  ALL_ALL   lt  DTS_SUBDOM = ALL_ALL           9
15  ALL_ALL   lv  DTS_SUBDOM = ALL_ALL           9
16  ALL_ALL   mt  DTS_SUBDOM = ALL_ALL           9
17  ALL_ALL   nl  DTS_SUBDOM = ALL_ALL          11
18  ALL_ALL   pl  DTS_SUBDOM = ALL_ALL          11
19  ALL_ALL   pt  DTS_SUBDOM = ALL_ALL          10

## Build query chunks

In [4]:
query_chunks = build_job_chunks(jobs, fields=FIELDS, terms_per_query=TERMS_PER_QUERY)
preview_df("query_chunks", query_chunks, n=14)
display(query_chunks[["job_index", "chunk_index", "scope", "lang", "term_count", "fields", "term_group"]].head(20))

query_chunks: shape=(54, 10)

,job_index,chunk_index,scope,lang,expert_scope,fields,term_count,terms,term_group,expert_query
0,1,1,ALL_ALL,en,DTS_SUBDOM = ALL_ALL,"TI, TE",12,"[nature-positive, nature positive, nature inclusive, nature-inclusive, nature-inclusive, nature inclusive design, nature based solutions, nature-based solutions, biodiversity net gain, biodiversity net-gain, biodiver...",nature-positive | nature positive | nature inclusive | nature-inclusive | nature-inclusive | nature inclusive design | nature based solutions | nature-based solutions | biodiversity net gain | biodiversity net-gain |...,"DTS_SUBDOM = ALL_ALL AND (((TI ~ ""nature-positive"" OR TE ~ ""nature-positive"")) OR ((TI ~ ""nature positive"" OR TE ~ ""nature positive"")) OR ((TI ~ ""nature inclusive"" OR TE ~ ""nature inclusive"")) OR ((TI ~ ""nature-inclu..."
1,1,2,ALL_ALL,en,DTS_SUBDOM = ALL_ALL,"TI, TE",2,"[nature repair, biodiversity strategy]",nature repair | biodiversity strategy,"DTS_SUBDOM = ALL_ALL AND (((TI ~ ""nature repair"" OR TE ~ ""nature repair"")) OR ((TI ~ ""biodiversity strategy"" OR TE ~ ""biodiversity strategy"")))"
2,2,1,ALL_ALL,bg,DTS_SUBDOM = ALL_ALL,"TI, TE",8,"[интегриран с природата дизайн, природосъобразен дизайн, природопозитивен, природосъобразни решения, стратегия за биологичното разнообразие, стратегия на ЕС за биологичното разнообразие, възстановяване на природата, ...",интегриран с природата дизайн | природосъобразен дизайн | природопозитивен | природосъобразни решения | стратегия за биологичното разнообразие | стратегия на ЕС за биологичното разнообразие | възстановяване на природ...,"DTS_SUBDOM = ALL_ALL AND (((TI ~ ""интегриран с природата дизайн"" OR TE ~ ""интегриран с природата дизайн"")) OR ((TI ~ ""природосъобразен дизайн"" OR TE ~ ""природосъобразен дизайн"")) OR ((TI ~ ""природопозитивен"" OR TE ~ ..."
3,3,1,ALL_ALL,cs,DTS_SUBDOM = ALL_ALL,"TI, TE",7,"[návrh zahrnující přírodu, pozitivní pro přírodu, řešení založená na přírodě, strategie v oblasti biologické rozmanitosti, strategie EU v oblasti biologické rozmanitosti, obnova přírody, obnova ekosystémů]",návrh zahrnující přírodu | pozitivní pro přírodu | řešení založená na přírodě | strategie v oblasti biologické rozmanitosti | strategie EU v oblasti biologické rozmanitosti | obnova přírody | obnova ekosystémů,"DTS_SUBDOM = ALL_ALL AND (((TI ~ ""návrh zahrnující přírodu"" OR TE ~ ""návrh zahrnující přírodu"")) OR ((TI ~ ""pozitivní pro přírodu"" OR TE ~ ""pozitivní pro přírodu"")) OR ((TI ~ ""řešení založená na přírodě"" OR TE ~ ""řeš..."
4,4,1,ALL_ALL,da,DTS_SUBDOM = ALL_ALL,"TI, TE",8,"[naturinkluderende, naturinkluderende design, naturpositiv, naturbaserede løsninger, biodiversitetsstrategi, EU's biodiversitetsstrategi, genopretning af natur, genopretning af biodiversitet]",naturinkluderende | naturinkluderende design | naturpositiv | naturbaserede løsninger | biodiversitetsstrategi | EU's biodiversitetsstrategi | genopretning af natur | genopretning af biodiversitet,"DTS_SUBDOM = ALL_ALL AND (((TI ~ ""naturinkluderende"" OR TE ~ ""naturinkluderende"")) OR ((TI ~ ""naturinkluderende design"" OR TE ~ ""naturinkluderende design"")) OR ((TI ~ ""naturpositiv"" OR TE ~ ""naturpositiv"")) OR ((TI ~..."
5,5,1,ALL_ALL,de,DTS_SUBDOM = ALL_ALL,"TI, TE",10,"[naturverträgliche Planung, naturpositiv, naturbasierte Lösungen, naturbasierte Lösung, Netto-Gewinn, Netto-Gewinn für die Biodiversität, Biodiversitätsstrategie, EU-Biodiversitätsstrategie, Wiederherstellung der Nat...",naturverträgliche Planung | naturpositiv | naturbasierte Lösungen | naturbasierte Lösung | Netto-Gewinn | Netto-Gewinn für die Biodiversität | Biodiversitätsstrategie | EU-Biodiversitätsstrategie | Wiederherstellung ...,"DTS_SUBDOM = ALL_ALL AND (((TI ~ ""naturverträgliche Planung"" OR TE ~ ""naturverträgliche Planung"")) OR ((TI ~ ""naturpositiv"" OR TE ~ ""naturpositiv"")) OR ((TI ~ ""naturbasierte Lösungen"" OR TE ~ ""naturbasierte Lösungen""..."
6,6,1,ALL_ALL,el,DTS_SUBDOM = ALL_ALL,"TI, TE",9,"[φιλικός προς τη φύση σχεδιασμός, θετικός για τη φύση, λύσεις βασισμένες στη φύση, καθαρό περιβαλλοντικό κέρδος, καθαρό κέρδος για τη βιοποικιλότητα, στρατηγική για τη βιοποικιλότητα, στρατηγική της ΕΕ για τη βιοποικ...",φιλικός προς τη φύση σχεδιασμός | θετικός για τη φύση | λύσεις βασισμένες στη φύση | καθαρό περιβαλλοντικό κέρδος | καθαρό κέρδος για τη βιοποικιλότητα | στρατηγική για τη βιοποικιλότητα | στρατηγική της ΕΕ για τη βι...,"DTS_SUBDOM = ALL_ALL AND (((TI ~ ""φιλικός προς τη φύση σχεδιασμός"" OR TE ~ ""φιλικός προς τη φύση σχεδιασμός"")) OR ((TI ~ ""θετικός για τη φύση"" OR TE ~ ""θετικός για τη φύση"")) OR ((TI ~ ""λύσεις βασισμένες στη φύση"" OR..."
7,7,1,ALL_ALL,es,DTS_SUBDOM = ALL_ALL,"TI, TE",11,"[diseño respetuoso con la naturaleza, positivo para la naturaleza, soluciones basadas en la naturaleza, ganancia neta, ganancia neta en biodiversidad, ganancia neta para la biodiversidad, estrategia de biodiversidad,...",diseño respetuoso con la naturaleza | positivo para la naturaleza | soluciones basadas en la naturaleza | ganancia neta | ganancia neta en biodiversidad | ganancia neta para la biodiversidad | estrategia de biodivers...,"DTS_SUBDOM = ALL_ALL AND (((TI ~ ""diseño respetuoso con la naturaleza"" OR TE ~ ""diseño respetuoso con la naturaleza"")) OR ((TI ~ ""positivo para la naturaleza"" OR TE ~ ""positivo para la naturaleza"")) OR ((TI ~ ""soluci..."
8,8,1,ALL_ALL,et,DTS_SUBDOM = ALL_ALL,"TI, TE",8,"[loodusega arvestav disain, looduspositiivne, looduspõhised lahendused, looduspõhine lahendus, elurikkuse strateegia, ELi elurikkuse strateegia, looduse taastamine, ökosüsteemide taastamine]",loodusega arvestav disain | looduspositiivne | looduspõhised lahendused | looduspõhine lahendus | elurikkuse strateegia | ELi elurikkuse strateegia | looduse taastamine | ökosüsteemide taastamine,"DTS_SUBDOM = ALL_ALL AND (((TI ~ ""loodusega arvestav disain"" OR TE ~ ""loodusega arvestav disain"")) OR ((TI ~ ""looduspositiivne"" OR TE ~ ""looduspositiivne"")) OR ((TI ~ ""looduspõhised lahendused"" OR TE ~ ""looduspõhised..."
9,9,1,ALL_ALL,fi,DTS_SUBDOM = ALL_ALL,"TI, TE",8,"[luontoystävällinen suunnittelu, luontopositiivinen, luontoon perustuvat ratkaisut, luontopohjaiset ratkaisut, biodiversiteettistrategia, EU:n biodiversiteettistrategia, luonnon ennallistaminen, ekosysteemien ennalli...",luontoystävällinen suunnittelu | luontopositiivinen | luontoon perustuvat ratkaisut | luontopohjaiset ratkaisut | biodiversiteettistrategia | EU:n biodiversiteettistrategia | luonnon ennallistaminen | ekosysteemien e...,"DTS_SUBDOM = ALL_ALL AND (((TI ~ ""luontoystävällinen suunnittelu"" OR TE ~ ""luontoystävällinen suunnittelu"")) OR ((TI ~ ""luontopositiivinen"" OR TE ~ ""luontopositiivinen"")) OR ((TI ~ ""luontoon perustuvat ratkaisut"" OR ..."
10,10,1,ALL_ALL,fr,DTS_SUBDOM = ALL_ALL,"TI, TE",10,"[aménagement respectueux de la nature, positif pour la nature, solutions fondées sur la nature, solution fondée sur la nature, gain net, gain net pour la biodiversité, stratégie pour la biodiversité, stratégie de l'U...",aménagement respectueux de la nature | positif pour la nature | solutions fondées sur la nature | solution fondée sur la nature | gain net | gain net pour la biodiversité | stratégie pour la biodiversité | stratégie ...,"DTS_SUBDOM = ALL_ALL AND (((TI ~ ""aménagement respectueux de la nature"" OR TE ~ ""aménagement respectueux de la nature"")) OR ((TI ~ ""positif pour la nature"" OR TE ~ ""positif pour la nature"")) OR ((TI ~ ""solutions fond..."
11,11,1,ALL_ALL,hr,DTS_SUBDOM = ALL_ALL,"TI, TE",10,"[dizajn usklađen s prirodom, pozitivan za prirodu, rješenja temeljena na prirodi, rješenja utemeljena na prirodi, neto dobitak za prirodu, neto dobitak za bioraznolikost, strategija bioraznolikosti, strategija EU-a z...",dizajn usklađen s prirodom | pozitivan za prirodu | rješenja temeljena na prirodi | rješenja utemeljena na prirodi | neto dobitak za prirodu | neto dobitak za bioraznolikost | strategija bioraznolikosti | strategija ...,"DTS_SUBDOM = ALL_ALL AND (((TI ~ ""dizajn usklađen s prirodom"" OR TE ~ ""dizajn usklađen s prirodom"")) OR ((TI ~ ""pozitivan za prirodu"" OR TE ~ ""pozitivan za prirodu"")) OR ((TI ~ ""rješenja temeljena na prirodi"" OR TE ~..."
12,12,1,ALL_ALL,hu,DTS_SUBDOM = ALL_ALL,"TI, TE",9,"[természetközeli tervezés, természetpozitív, természetalapú megoldások, nettó természetnyereség, nettó biodiverzitásnyereség, biodiverzitás-stratégia, uniós biodiverzitás-stratégia, a természet helyreállítása, ökoszi...",természetközeli tervezés | természetpozitív | természetalapú megoldások | nettó természetnyereség | nettó biodiverzitásnyereség | biodiverzitás-stratégia | uniós biodiverzitás-stratégia | a természet helyreállítása |...,"DTS_SUBDOM = ALL_ALL AND (((TI ~ ""természetközeli tervezés"" OR TE ~ ""természetközeli tervezés"")) OR ((TI ~ ""természetpozitív"" OR TE ~ ""természetpozitív"")) OR ((TI ~ ""természetalapú megoldások"" OR TE ~ ""természetalapú..."
13,13,1,ALL_ALL,ga,DTS_SUBDOM = ALL_ALL,"TI, TE",10,"[dearadh atá comhtháite leis an dúlra, dearfach don dúlra, réitigh bunaithe ar an dúlra, réitigh atá bunaithe ar an dúlra, glanbuntáiste don dúlra, glanbuntáiste don bhithéagsúlacht, straitéis bithéagsúlachta, strait...",dearadh atá comhtháite leis an dúlra | dearfach don dúlra | réitigh bunaithe ar an dúlra | réitigh atá bunaithe ar an dúlra | glanbuntáiste don dúlra | glanbuntáiste don bhithéagsúlacht | straitéis bithéagsúlachta | ...,"DTS_SUBDOM = ALL_ALL AND (((TI ~ ""dearadh atá comhtháite leis an dúlra"" OR TE ~ ""dearadh atá comhtháite leis an dúlra"")) OR ((TI ~ ""dearfach don dúlra"" OR TE ~ ""dearfach don dúlra"")) OR ((TI ~ ""réitigh bunaithe ar an..."

,job_index,chunk_index,scope,lang,term_count,fields,term_group
0,1,1,ALL_ALL,en,12,"TI, TE",nature-positive | nature positive | nature inclusive | nature-inclusive | nature-inclusive | nature inclusive design | nature based solutions | nature-based solutions | biodiversity net gain | biodiversity net-gain |...
1,1,2,ALL_ALL,en,2,"TI, TE",nature repair | biodiversity strategy
2,2,1,ALL_ALL,bg,8,"TI, TE",интегриран с природата дизайн | природосъобразен дизайн | природопозитивен | природосъобразни решения | стратегия за биологичното разнообразие | стратегия на ЕС за биологичното разнообразие | възстановяване на природ...
3,3,1,ALL_ALL,cs,7,"TI, TE",návrh zahrnující přírodu | pozitivní pro přírodu | řešení založená na přírodě | strategie v oblasti biologické rozmanitosti | strategie EU v oblasti biologické rozmanitosti | obnova přírody | obnova ekosystémů
4,4,1,ALL_ALL,da,8,"TI, TE",naturinkluderende | naturinkluderende design | naturpositiv | naturbaserede løsninger | biodiversitetsstrategi | EU's biodiversitetsstrategi | genopretning af natur | genopretning af biodiversitet
5,5,1,ALL_ALL,de,10,"TI, TE",naturverträgliche Planung | naturpositiv | naturbasierte Lösungen | naturbasierte Lösung | Netto-Gewinn | Netto-Gewinn für die Biodiversität | Biodiversitätsstrategie | EU-Biodiversitätsstrategie | Wiederherstellung ...
6,6,1,ALL_ALL,el,9,"TI, TE",φιλικός προς τη φύση σχεδιασμός | θετικός για τη φύση | λύσεις βασισμένες στη φύση | καθαρό περιβαλλοντικό κέρδος | καθαρό κέρδος για τη βιοποικιλότητα | στρατηγική για τη βιοποικιλότητα | στρατηγική της ΕΕ για τη βι...
7,7,1,ALL_ALL,es,11,"TI, TE",diseño respetuoso con la naturaleza | positivo para la naturaleza | soluciones basadas en la naturaleza | ganancia neta | ganancia neta en biodiversidad | ganancia neta para la biodiversidad | estrategia de biodivers...
8,8,1,ALL_ALL,et,8,"TI, TE",loodusega arvestav disain | looduspositiivne | looduspõhised lahendused | looduspõhine lahendus | elurikkuse strateegia | ELi elurikkuse strateegia | looduse taastamine | ökosüsteemide taastamine
9,9,1,ALL_ALL,fi,8,"TI, TE",luontoystävällinen suunnittelu | luontopositiivinen | luontoon perustuvat ratkaisut | luontopohjaiset ratkaisut | biodiversiteettistrategia | EU:n biodiversiteettistrategia | luonnon ennallistaminen | ekosysteemien e...
10,10,1,ALL_ALL,fr,10,"TI, TE",aménagement respectueux de la nature | positif pour la nature | solutions fondées sur la nature | solution fondée sur la nature | gain net | gain net pour la biodiversité | stratégie pour la biodiversité | stratégie ...
11,11,1,ALL_ALL,hr,10,"TI, TE",dizajn usklađen s prirodom | pozitivan za prirodu | rješenja temeljena na prirodi | rješenja utemeljena na prirodi | neto dobitak za prirodu | neto dobitak za bioraznolikost | strategija bioraznolikosti | strategija ...
12,12,1,ALL_ALL,hu,9,"TI, TE",természetközeli tervezés | természetpozitív | természetalapú megoldások | nettó természetnyereség | nettó biodiverzitásnyereség | biodiverzitás-stratégia | uniós biodiverzitás-stratégia | a természet helyreállítása |...
13,13,1,ALL_ALL,ga,10,"TI, TE",dearadh atá comhtháite leis an dúlra | dearfach don dúlra | réitigh bunaithe ar an dúlra | réitigh atá bunaithe ar an dúlra | glanbuntáiste don dúlra | glanbuntáiste don bhithéagsúlacht | straitéis bithéagsúlachta | ...
14,14,1,ALL_ALL,it,11,"TI, TE",progettazione a favore della natura | positivo per la natura | soluzioni basate sulla natura | soluzione basata sulla natura | guadagno netto | guadagno netto di biodiversità | guadagno netto per la biodiversità | st...
15,15,1,ALL_ALL,lt,9,"TI, TE",su gamta suderintas dizainas | teigiamas gamtai | gamtos procesais pagrįsti sprendimai | grynasis aplinkosaugos pelnas | grynasis biologinės įvairovės prieaugis | biologinės įvairovės strategija | ES biologinės įvair...
16,16,1,ALL_ALL,lv,9,"TI, TE",dizains saskaņā ar dabu | pozitīvs dabai | dabā balstīti risinājumi | neto ieguvums dabai | neto ieguvums bioloģiskajai daudzveidībai | bioloģiskās daudzveidības stratēģija | ES bioloģiskās daudzveidības stratēģija |...
17,17,1,ALL_ALL,mt,9,"TI, TE",disinn li jinkludi n-natura | pożittiv għan-natura | soluzzjonijiet ibbażati fuq in-natura | qligħ nett għall-ambjent | qligħ nett għall-bijodiversità | strateġija tal-bijodiversità | strateġija tal-UE għall-bijodive...
18,18,1,ALL_ALL,nl,11,"TI, TE",natuurinclusief ontwerp | natuurinclusief | natuurpositief | op de natuur gebaseerde oplossingen | natuurgebaseerde oplossingen | netto natuurwinst | netto biodiversiteitswinst | biodiversiteitsstrategie | EU-biodive...
19,19,1,ALL_ALL,pl,11,"TI, TE",projektowanie przyjazne przyrodzie | pozytywny dla przyrody | rozwiązania oparte na przyrodzie | rozwiązania oparte na zasobach przyrody | zysk netto dla środowiska | zysk netto dla bioróżnorodności | strategia na rz...

## Parser debug probe: run one small live SOAP query and inspect the raw XML

In [ ]:
debug_probe_status = "not_run"
debug_probe_raw = ""
debug_probe_rows = []
debug_probe_diag_df = pd.DataFrame()
debug_probe_snippets = []

if RUN_LIVE and RUN_PARSER_DEBUG_PROBE and not query_chunks.empty:
    debug_row = query_chunks.iloc[0]
    debug_terms = list(debug_row["terms"][:DEBUG_TERM_LIMIT]) if isinstance(debug_row["terms"], list) else []
    debug_query = build_expert_query(debug_row["expert_scope"], debug_terms, fields=FIELDS)
    debug_payload = build_soap_envelope(
        debug_query,
        page=1,
        page_size=DEBUG_PAGE_SIZE,
        lang=debug_row["lang"],
    )
    debug_probe_raw, debug_status_code, _debug_body = post_eurlex_ws(
        debug_payload,
        timeout=TIMEOUT_S,
        retry_5xx=RETRY_5XX,
        min_interval_s=0,
        debug=DEBUG,
    )
    if debug_probe_raw:
        DEBUG_XML_PATH.write_text(debug_probe_raw, encoding="utf-8")
        debug_probe_status = f"live_ok_status_{debug_status_code}"
        totalhits, numhits, debug_probe_rows, missing_celex = parse_searchresults(debug_probe_raw, lang_for_url="EN")
        debug_probe_diag_df = build_result_diagnostics(debug_probe_raw, preferred_lang="en", limit=3)
        debug_probe_snippets = extract_result_snippets(debug_probe_raw, limit=2, max_chars=3500)
        print("Saved raw XML to", DEBUG_XML_PATH)
        print("totalhits =", totalhits)
        print("numhits =", numhits)
        print("hits_parsed =", len(debug_probe_rows))
        print("missing_celex =", missing_celex)
    else:
        debug_probe_status = f"live_failed_status_{debug_status_code}"

print("debug_probe_status =", debug_probe_status)

## Inspect parser diagnostics

In [ ]:
preview_df("debug_probe_parsed_rows", pd.DataFrame(debug_probe_rows))
preview_df("debug_probe_diag_df", debug_probe_diag_df)
for idx, snippet in enumerate(debug_probe_snippets, start=1):
    print(f"--- result snippet {idx} ---")
    print(snippet)
    print()

## Run the full EUR-Lex WebService retrieval

In [5]:
retrieval_mode = "live_webservice" if RUN_LIVE else "cached_rows"
live_error = ""
live_rows = []

if RUN_LIVE:
    try:
        live_rows = run_eurlex_jobs(
            jobs,
            fields=FIELDS,
            terms_per_query=TERMS_PER_QUERY,
            page_size=PAGE_SIZE,
            page_size_candidates=PAGE_SIZE_CANDIDATES,
            max_pages=MAX_PAGES,
            min_interval_s=MIN_INTERVAL_S,
            timeout=TIMEOUT_S,
            retry_5xx=RETRY_5XX,
            debug=DEBUG,
        )
    except Exception as exc:
        live_error = str(exc)
        retrieval_mode = "cached_rows" if ALLOW_FALLBACK else "live_failed"
        print("Live EUR-Lex WebService retrieval failed.")
        print(live_error)

print("retrieval_mode =", retrieval_mode)
print("live_rows =", len(live_rows))

=== JOB scope=ALL_ALL lang=en terms=14 groups=2 fields=('TI', 'TE') ===

[EURLEX] group 1/2 | terms=12
[EURLEX] trying page_size=100
[EURLEX] POST 6.56s status=200 bytes=1691815
[EURLEX] page=1 totalhits=1411 numhits=100 hits_parsed=53 missing_celex=47
[EURLEX] POST 5.34s status=200 bytes=1959362
[EURLEX] page=2 numhits=100 hits_parsed=63 missing_celex=37
[EURLEX] POST 6.34s status=200 bytes=1746134
[EURLEX] page=3 numhits=100 hits_parsed=82 missing_celex=18
[EURLEX] POST 5.92s status=200 bytes=1860048
[EURLEX] page=4 numhits=100 hits_parsed=65 missing_celex=35
[EURLEX] POST 5.51s status=200 bytes=1796904
[EURLEX] page=5 numhits=100 hits_parsed=62 missing_celex=38
[EURLEX] POST 7.38s status=200 bytes=1627366
[EURLEX] page=6 numhits=100 hits_parsed=66 missing_celex=34
[EURLEX] POST 5.04s status=200 bytes=1584225
[EURLEX] page=7 numhits=100 hits_parsed=67 missing_celex=33
[EURLEX] POST 6.60s status=200 bytes=1661908
[EURLEX] page=8 numhits=100 hits_parsed=65 missing_celex=35
[EURLEX] POST 6.53s status=200 bytes=1657124
[EURLEX] page=9 numhits=100 hits_parsed=72 missing_celex=28
[EURLEX] POST 7.64s status=200 bytes=1454371
[EURLEX] page=10 numhits=100 hits_parsed=76 missing_celex=24
[EURLEX] POST 11.89s status=200 bytes=1674196
[EURLEX] page=11 numhits=100 hits_parsed=63 missing_celex=37
[EURLEX] POST 12.83s status=200 bytes=1425635
[EURLEX] page=12 numhits=100 hits_parsed=67 missing_celex=33
[EURLEX] POST 11.11s status=200 bytes=1538499
[EURLEX] page=13 numhits=100 hits_parsed=61 missing_celex=39
[EURLEX] POST 23.11s status=200 bytes=1725942
[EURLEX] page=14 numhits=100 hits_parsed=62 missing_celex=38
[EURLEX] POST 5.53s status=200 bytes=235637
[EURLEX] page=15 numhits=11 hits_parsed=10 missing_celex=1

[EURLEX] group 2/2 | terms=2
[EURLEX] trying page_size=100
[EURLEX] POST 2.96s status=200 bytes=2003086
[EURLEX] page=1 totalhits=2009 numhits=100 hits_parsed=73 missing_celex=27
[EURLEX] POST 3.14s status=200 bytes=1962246
[EURLEX] page=2 numhits=100 hits_parsed=83 missing_celex=17
[EURLEX] POST 3.07s status=200 bytes=2010937
[EURLEX] page=3 numhits=100 hits_parsed=58 missing_celex=42
[EURLEX] POST 2.60s status=200 bytes=1863199
[EURLEX] page=4 numhits=100 hits_parsed=71 missing_celex=29
[EURLEX] POST 2.75s status=200 bytes=2141915
[EURLEX] page=5 numhits=100 hits_parsed=76 missing_celex=24
[EURLEX] POST 3.82s status=200 bytes=2006496
[EURLEX] page=6 numhits=100 hits_parsed=79 missing_celex=21
[EURLEX] POST 3.19s status=200 bytes=2244116
[EURLEX] page=7 numhits=100 hits_parsed=79 missing_celex=21
[EURLEX] POST 4.44s status=200 bytes=2012592
[EURLEX] page=8 numhits=100 hits_parsed=68 missing_celex=32
[EURLEX] POST 4.12s status=200 bytes=1988393
[EURLEX] page=9 numhits=100 hits_parsed=78 missing_celex=22
[EURLEX] POST 5.88s status=200 bytes=1629559
[EURLEX] page=10 numhits=100 hits_parsed=82 missing_celex=18
[EURLEX] POST 5.81s status=200 bytes=1876592
[EURLEX] page=11 numhits=100 hits_parsed=75 missing_celex=25
[EURLEX] POST 6.61s status=200 bytes=1515100
[EURLEX] page=12 numhits=100 hits_parsed=71 missing_celex=29
[EURLEX] POST 9.78s status=200 bytes=1552649
[EURLEX] page=13 numhits=100 hits_parsed=75 missing_celex=25
[EURLEX] POST 6.56s status=200 bytes=1557749
[EURLEX] page=14 numhits=100 hits_parsed=68 missing_celex=32
[EURLEX] POST 10.32s status=200 bytes=1689031
[EURLEX] page=15 numhits=100 hits_parsed=68 missing_celex=32
[EURLEX] POST 9.91s status=200 bytes=1659693
[EURLEX] page=16 numhits=100 hits_parsed=67 missing_celex=33
[EURLEX] POST 13.10s status=200 bytes=1776704
[EURLEX] page=17 numhits=100 hits_parsed=68 missing_celex=32
[EURLEX] POST 13.69s status=200 bytes=1596803
[EURLEX] page=18 numhits=100 hits_parsed=67 missing_celex=33
[EURLEX] POST 14.13s status=200 bytes=1650952
[EURLEX] page=19 numhits=100 hits_parsed=70 missing_celex=30
[EURLEX] POST 8.94s status=500 bytes=523
[EURLEX] POST 9.06s status=500 bytes=523
[EURLEX] POST 8.91s status=500 bytes=523
[EURLEX] POST 8.95s status=500 bytes=523
[EURLEX] page=20 failed (status=500) with page_size=100; retry with smaller.
[EURLEX] trying page_size=50
[EURLEX] POST 1.23s status=200 bytes=967386
[EURLEX] page=1 totalhits=2009 numhits=50 hits_parsed=40 missing_celex=10
[EURLEX] POST 2.23s status=200 bytes=1036297
[EURLEX] page=2 numhits=50 hits_parsed=33 missing_celex=17
[EURLEX] POST 1.55s status=200 bytes=1097908
[EURLEX] page=3 numhits=50 hits_parsed=40 missing_celex=10
[EURLEX] POST 1.90s status=200 bytes=839460
[EURLEX] page=4 numhits=50 hits_parsed=43 missing_celex=7
[EURLEX] POST 1.68s status=200 bytes=1075960
[EURLEX] page=5 numhits=50 hits_parsed=29 missing_celex=21
[EURLEX] POST 2.03s status=200 bytes=935574
[EURLEX] page=6 numhits=50 hits_parsed=29 missing_celex=21
[EURLEX] POST 1.47s status=200 bytes=922857
[EURLEX] page=7 numhits=50 hits_parsed=38 missing_celex=12
[EURLEX] POST 1.31s status=200 bytes=945539
[EURLEX] page=8 numhits=50 hits_parsed=35 missing_celex=15
[EURLEX] POST 1.56s status=200 bytes=1063052
[EURLEX] page=9 numhits=50 hits_parsed=35 missing_celex=15
[EURLEX] POST 1.61s status=200 bytes=1051769
[EURLEX] page=10 numhits=50 hits_parsed=41 missing_celex=9
[EURLEX] POST 2.36s status=200 bytes=971603
[EURLEX] page=11 numhits=50 hits_parsed=39 missing_celex=11
[EURLEX] POST 1.74s status=200 bytes=1036731
[EURLEX] page=12 numhits=50 hits_parsed=40 missing_celex=10
[EURLEX] POST 1.93s status=200 bytes=1056850
[EURLEX] page=13 numhits=50 hits_parsed=37 missing_celex=13
[EURLEX] POST 1.75s status=200 bytes=1189916
[EURLEX] page=14 numhits=50 hits_parsed=42 missing_celex=8
[EURLEX] POST 2.60s status=200 bytes=874321
[EURLEX] page=15 numhits=50 hits_parsed=30 missing_celex=20
[EURLEX] POST 2.01s status=200 bytes=1152211
[EURLEX] page=16 numhits=50 hits_parsed=38 missing_celex=12
[EURLEX] POST 2.60s status=200 bytes=910092
[EURLEX] page=17 numhits=50 hits_parsed=34 missing_celex=16
[EURLEX] POST 1.64s status=200 bytes=1078900
[EURLEX] page=18 numhits=50 hits_parsed=44 missing_celex=6
[EURLEX] POST 1.88s status=200 bytes=881494
[EURLEX] page=19 numhits=50 hits_parsed=43 missing_celex=7
[EURLEX] POST 4.20s status=200 bytes=748663
[EURLEX] page=20 numhits=50 hits_parsed=39 missing_celex=11
[EURLEX] POST 3.09s status=200 bytes=890456
[EURLEX] page=21 numhits=50 hits_parsed=39 missing_celex=11
[EURLEX] POST 3.64s status=200 bytes=986734
[EURLEX] page=22 numhits=50 hits_parsed=36 missing_celex=14
[EURLEX] POST 3.01s status=200 bytes=759499
[EURLEX] page=23 numhits=50 hits_parsed=30 missing_celex=20
[EURLEX] POST 3.94s status=200 bytes=756199
[EURLEX] page=24 numhits=50 hits_parsed=41 missing_celex=9
[EURLEX] POST 4.26s status=200 bytes=853126
[EURLEX] page=25 numhits=50 hits_parsed=37 missing_celex=13
[EURLEX] POST 5.85s status=200 bytes=699319
[EURLEX] page=26 numhits=50 hits_parsed=38 missing_celex=12
[EURLEX] POST 2.82s status=200 bytes=810748
[EURLEX] page=27 numhits=50 hits_parsed=40 missing_celex=10
[EURLEX] POST 3.75s status=200 bytes=767426
[EURLEX] page=28 numhits=50 hits_parsed=29 missing_celex=21
[EURLEX] POST 4.29s status=200 bytes=796680
[EURLEX] page=29 numhits=50 hits_parsed=29 missing_celex=21
[EURLEX] POST 6.00s status=200 bytes=872320
[EURLEX] page=30 numhits=50 hits_parsed=38 missing_celex=12
[EURLEX] POST 5.04s status=200 bytes=953384
[EURLEX] page=31 numhits=50 hits_parsed=32 missing_celex=18
[EURLEX] POST 4.92s status=200 bytes=706907
[EURLEX] page=32 numhits=50 hits_parsed=35 missing_celex=15
[EURLEX] POST 6.79s status=200 bytes=899165
[EURLEX] page=33 numhits=50 hits_parsed=39 missing_celex=11
[EURLEX] POST 7.17s status=200 bytes=878137
[EURLEX] page=34 numhits=50 hits_parsed=29 missing_celex=21
[EURLEX] POST 7.88s status=200 bytes=850175
[EURLEX] page=35 numhits=50 hits_parsed=27 missing_celex=23
[EURLEX] POST 5.46s status=200 bytes=747226
[EURLEX] page=36 numhits=50 hits_parsed=40 missing_celex=10
[EURLEX] POST 6.70s status=200 bytes=866757
[EURLEX] page=37 numhits=50 hits_parsed=33 missing_celex=17
[EURLEX] POST 8.10s status=200 bytes=784793
[EURLEX] page=38 numhits=50 hits_parsed=37 missing_celex=13
[EURLEX] POST 10.96s status=200 bytes=1119257
[EURLEX] page=39 numhits=50 hits_parsed=30 missing_celex=20
[EURLEX] POST 17.20s status=200 bytes=1467653
[EURLEX] page=40 numhits=50 hits_parsed=32 missing_celex=18
[EURLEX] POST 4.77s status=200 bytes=262600
[EURLEX] page=41 numhits=9 hits_parsed=7 missing_celex=2

=== JOB scope=ALL_ALL lang=bg terms=8 groups=1 fields=('TI', 'TE') ===

[EURLEX] group 1/1 | terms=8
[EURLEX] trying page_size=100
[EURLEX] POST 3.38s status=200 bytes=2564524
[EURLEX] page=1 totalhits=1167 numhits=100 hits_parsed=74 missing_celex=26
[EURLEX] POST 3.72s status=200 bytes=2133301
[EURLEX] page=2 numhits=100 hits_parsed=62 missing_celex=38
[EURLEX] POST 3.54s status=200 bytes=2329896
[EURLEX] page=3 numhits=100 hits_parsed=81 missing_celex=19
[EURLEX] POST 3.69s status=200 bytes=2416300
[EURLEX] page=4 numhits=100 hits_parsed=70 missing_celex=30
[EURLEX] POST 4.30s status=200 bytes=2467975
[EURLEX] page=5 numhits=100 hits_parsed=73 missing_celex=27
[EURLEX] POST 4.61s status=200 bytes=2283808
[EURLEX] page=6 numhits=100 hits_parsed=68 missing_celex=32
[EURLEX] POST 7.20s status=200 bytes=2297894
[EURLEX] page=7 numhits=100 hits_parsed=65 missing_celex=35
[EURLEX] POST 10.23s status=200 bytes=2040697
[EURLEX] page=8 numhits=100 hits_parsed=49 missing_celex=51
[EURLEX] POST 9.95s status=200 bytes=2148103
[EURLEX] page=9 numhits=100 hits_parsed=66 missing_celex=34
[EURLEX] POST 8.23s status=200 bytes=2268955
[EURLEX] page=10 numhits=100 hits_parsed=60 missing_celex=40
[EURLEX] POST 18.75s status=200 bytes=2092121
[EURLEX] page=11 numhits=100 hits_parsed=50 missing_celex=50
[EURLEX] POST 6.83s status=500 bytes=523
[EURLEX] POST 6.57s status=500 bytes=523
[EURLEX] POST 6.55s status=500 bytes=523
[EURLEX] POST 6.68s status=500 bytes=523
[EURLEX] page=12 failed (status=500) with page_size=100; retry with smaller.
[EURLEX] trying page_size=50
[EURLEX] POST 1.81s status=200 bytes=1369909
[EURLEX] page=1 totalhits=1167 numhits=50 hits_parsed=38 missing_celex=12
[EURLEX] POST 1.82s status=200 bytes=1195212
[EURLEX] page=2 numhits=50 hits_parsed=36 missing_celex=14
[EURLEX] POST 2.36s status=200 bytes=1037252
[EURLEX] page=3 numhits=50 hits_parsed=20 missing_celex=30
[EURLEX] POST 1.48s status=200 bytes=1096646
[EURLEX] page=4 numhits=50 hits_parsed=42 missing_celex=8
[EURLEX] POST 1.65s status=200 bytes=1116062
[EURLEX] page=5 numhits=50 hits_parsed=41 missing_celex=9
[EURLEX] POST 2.40s status=200 bytes=1214431
[EURLEX] page=6 numhits=50 hits_parsed=40 missing_celex=10
[EURLEX] POST 2.00s status=200 bytes=1175101
[EURLEX] page=7 numhits=50 hits_parsed=36 missing_celex=14
[EURLEX] POST 2.11s status=200 bytes=1241796
[EURLEX] page=8 numhits=50 hits_parsed=34 missing_celex=16
[EURLEX] POST 2.09s status=200 bytes=1283822
[EURLEX] page=9 numhits=50 hits_parsed=36 missing_celex=14
[EURLEX] POST 2.42s status=200 bytes=1135462
[EURLEX] page=10 numhits=50 hits_parsed=35 missing_celex=15
[EURLEX] POST 2.38s status=200 bytes=1200377
[EURLEX] page=11 numhits=50 hits_parsed=33 missing_celex=17
[EURLEX] POST 2.34s status=200 bytes=1047858
[EURLEX] page=12 numhits=50 hits_parsed=35 missing_celex=15
[EURLEX] POST 2.77s status=200 bytes=1237734
[EURLEX] page=13 numhits=50 hits_parsed=29 missing_celex=21
[EURLEX] POST 5.10s status=200 bytes=1060759
[EURLEX] page=14 numhits=50 hits_parsed=36 missing_celex=14
[EURLEX] POST 6.63s status=200 bytes=987855
[EURLEX] page=15 numhits=50 hits_parsed=23 missing_celex=27
[EURLEX] POST 4.97s status=200 bytes=1053441
[EURLEX] page=16 numhits=50 hits_parsed=26 missing_celex=24
[EURLEX] POST 5.36s status=200 bytes=1084214
[EURLEX] page=17 numhits=50 hits_parsed=31 missing_celex=19
[EURLEX] POST 4.31s status=200 bytes=1064488
[EURLEX] page=18 numhits=50 hits_parsed=35 missing_celex=15
[EURLEX] POST 3.87s status=200 bytes=1067901
[EURLEX] page=19 numhits=50 hits_parsed=28 missing_celex=22
[EURLEX] POST 5.49s status=200 bytes=1201652
[EURLEX] page=20 numhits=50 hits_parsed=32 missing_celex=18
[EURLEX] POST 8.04s status=200 bytes=1106304
[EURLEX] page=21 numhits=50 hits_parsed=24 missing_celex=26
[EURLEX] POST 8.22s status=200 bytes=986415
[EURLEX] page=22 numhits=50 hits_parsed=26 missing_celex=24
[EURLEX] POST 12.31s status=200 bytes=947461
[EURLEX] page=23 numhits=50 hits_parsed=34 missing_celex=16
[EURLEX] POST 9.64s status=200 bytes=461343
[EURLEX] page=24 numhits=17 hits_parsed=17 missing_celex=0

=== JOB scope=ALL_ALL lang=cs terms=7 groups=1 fields=('TI', 'TE') ===

[EURLEX] group 1/1 | terms=7
[EURLEX] trying page_size=100
[EURLEX] POST 3.24s status=200 bytes=2345752
[EURLEX] page=1 totalhits=994 numhits=100 hits_parsed=74 missing_celex=26
[EURLEX] POST 2.45s status=200 bytes=2443938
[EURLEX] page=2 numhits=100 hits_parsed=63 missing_celex=37
[EURLEX] POST 2.56s status=200 bytes=2373740
[EURLEX] page=3 numhits=100 hits_parsed=67 missing_celex=33
[EURLEX] POST 3.10s status=200 bytes=2628055
[EURLEX] page=4 numhits=100 hits_parsed=75 missing_celex=25
[EURLEX] POST 2.84s status=200 bytes=2626055
[EURLEX] page=5 numhits=100 hits_parsed=71 missing_celex=29
[EURLEX] POST 5.25s status=200 bytes=2599975
[EURLEX] page=6 numhits=100 hits_parsed=71 missing_celex=29
[EURLEX] POST 5.89s status=200 bytes=2246030
[EURLEX] page=7 numhits=100 hits_parsed=70 missing_celex=30
[EURLEX] POST 6.29s status=200 bytes=2199946
[EURLEX] page=8 numhits=100 hits_parsed=61 missing_celex=39
[EURLEX] POST 9.18s status=200 bytes=2450812
[EURLEX] page=9 numhits=100 hits_parsed=65 missing_celex=35
[EURLEX] POST 18.37s status=200 bytes=2353749
[EURLEX] page=10 numhits=94 hits_parsed=61 missing_celex=33

=== JOB scope=ALL_ALL lang=da terms=8 groups=1 fields=('TI', 'TE') ===

[EURLEX] group 1/1 | terms=8
[EURLEX] trying page_size=100
[EURLEX] POST 6.06s status=200 bytes=2556021
[EURLEX] page=1 totalhits=1554 numhits=100 hits_parsed=76 missing_celex=24
[EURLEX] POST 2.80s status=200 bytes=2333831
[EURLEX] page=2 numhits=100 hits_parsed=59 missing_celex=41
[EURLEX] POST 2.74s status=200 bytes=2400763
[EURLEX] page=3 numhits=100 hits_parsed=75 missing_celex=25
[EURLEX] POST 4.00s status=200 bytes=2338074
[EURLEX] page=4 numhits=100 hits_parsed=73 missing_celex=27
[EURLEX] POST 3.21s status=200 bytes=2648944
[EURLEX] page=5 numhits=100 hits_parsed=83 missing_celex=17
[EURLEX] POST 3.62s status=200 bytes=2168067
[EURLEX] page=6 numhits=100 hits_parsed=73 missing_celex=27
[EURLEX] POST 4.44s status=200 bytes=2500272
[EURLEX] page=7 numhits=100 hits_parsed=79 missing_celex=21
[EURLEX] POST 3.44s status=200 bytes=2198710
[EURLEX] page=8 numhits=100 hits_parsed=75 missing_celex=25
[EURLEX] POST 6.97s status=200 bytes=2206079
[EURLEX] page=9 numhits=100 hits_parsed=63 missing_celex=37
[EURLEX] POST 5.33s status=200 bytes=2158464
[EURLEX] page=10 numhits=100 hits_parsed=59 missing_celex=41
[EURLEX] POST 5.66s status=200 bytes=2214991
[EURLEX] page=11 numhits=100 hits_parsed=63 missing_celex=37
[EURLEX] POST 9.82s status=200 bytes=2098969
[EURLEX] page=12 numhits=100 hits_parsed=61 missing_celex=39
[EURLEX] POST 8.42s status=200 bytes=2108841
[EURLEX] page=13 numhits=100 hits_parsed=67 missing_celex=33
[EURLEX] POST 9.09s status=200 bytes=2355880
[EURLEX] page=14 numhits=100 hits_parsed=59 missing_celex=41
[EURLEX] POST 19.50s status=200 bytes=2199850
[EURLEX] page=15 numhits=100 hits_parsed=62 missing_celex=38
[EURLEX] POST 15.09s status=200 bytes=1237004
[EURLEX] page=16 numhits=54 hits_parsed=32 missing_celex=22

=== JOB scope=ALL_ALL lang=de terms=10 groups=1 fields=('TI', 'TE') ===

[EURLEX] group 1/1 | terms=10
[EURLEX] trying page_size=100
[EURLEX] POST 3.47s status=200 bytes=2231555
[EURLEX] page=1 totalhits=1765 numhits=100 hits_parsed=69 missing_celex=31
[EURLEX] POST 4.94s status=200 bytes=2375092
[EURLEX] page=2 numhits=100 hits_parsed=64 missing_celex=36
[EURLEX] POST 2.85s status=200 bytes=2283692
[EURLEX] page=3 numhits=100 hits_parsed=65 missing_celex=35
[EURLEX] POST 4.02s status=200 bytes=2246594
[EURLEX] page=4 numhits=100 hits_parsed=70 missing_celex=30
[EURLEX] POST 3.33s status=200 bytes=2378754
[EURLEX] page=5 numhits=100 hits_parsed=67 missing_celex=33
[EURLEX] POST 4.19s status=200 bytes=2161783
[EURLEX] page=6 numhits=100 hits_parsed=76 missing_celex=24
[EURLEX] POST 4.28s status=200 bytes=2347468
[EURLEX] page=7 numhits=100 hits_parsed=69 missing_celex=31
[EURLEX] POST 5.84s status=200 bytes=2164326
[EURLEX] page=8 numhits=100 hits_parsed=52 missing_celex=48
[EURLEX] POST 5.23s status=200 bytes=2257400
[EURLEX] page=9 numhits=100 hits_parsed=66 missing_celex=34
[EURLEX] POST 5.16s status=200 bytes=2397534
[EURLEX] page=10 numhits=100 hits_parsed=69 missing_celex=31
[EURLEX] POST 6.61s status=200 bytes=2418587
[EURLEX] page=11 numhits=100 hits_parsed=72 missing_celex=28
[EURLEX] POST 7.77s status=200 bytes=2357525
[EURLEX] page=12 numhits=100 hits_parsed=67 missing_celex=33
[EURLEX] POST 6.70s status=200 bytes=2097860
[EURLEX] page=13 numhits=100 hits_parsed=64 missing_celex=36
[EURLEX] POST 6.36s status=200 bytes=2150062
[EURLEX] page=14 numhits=100 hits_parsed=70 missing_celex=30
[EURLEX] POST 11.01s status=200 bytes=2019623
[EURLEX] page=15 numhits=100 hits_parsed=53 missing_celex=47
[EURLEX] POST 10.63s status=200 bytes=2050966
[EURLEX] page=16 numhits=100 hits_parsed=65 missing_celex=35
[EURLEX] POST 20.96s status=200 bytes=2235562
[EURLEX] page=17 numhits=100 hits_parsed=64 missing_celex=36
[EURLEX] POST 8.68s status=500 bytes=523
[EURLEX] POST 8.00s status=500 bytes=523
[EURLEX] POST 7.94s status=500 bytes=523
[EURLEX] POST 8.66s status=500 bytes=523
[EURLEX] page=18 failed (status=500) with page_size=100; retry with smaller.
[EURLEX] trying page_size=50
[EURLEX] POST 2.12s status=200 bytes=1122986
[EURLEX] page=1 totalhits=1765 numhits=50 hits_parsed=33 missing_celex=17
[EURLEX] POST 1.49s status=200 bytes=1109166
[EURLEX] page=2 numhits=50 hits_parsed=36 missing_celex=14
[EURLEX] POST 2.42s status=200 bytes=1343439
[EURLEX] page=3 numhits=50 hits_parsed=36 missing_celex=14
[EURLEX] POST 3.14s status=200 bytes=1031357
[EURLEX] page=4 numhits=50 hits_parsed=28 missing_celex=22
[EURLEX] POST 1.68s status=200 bytes=1060101
[EURLEX] page=5 numhits=50 hits_parsed=35 missing_celex=15
[EURLEX] POST 1.71s status=200 bytes=1221382
[EURLEX] page=6 numhits=50 hits_parsed=31 missing_celex=19
[EURLEX] POST 1.81s status=200 bytes=1199826
[EURLEX] page=7 numhits=50 hits_parsed=35 missing_celex=15
[EURLEX] POST 2.51s status=200 bytes=1053507
[EURLEX] page=8 numhits=50 hits_parsed=35 missing_celex=15
[EURLEX] POST 2.00s status=200 bytes=1278681
[EURLEX] page=9 numhits=50 hits_parsed=36 missing_celex=14
[EURLEX] POST 1.63s status=200 bytes=1114591
[EURLEX] page=10 numhits=50 hits_parsed=32 missing_celex=18
[EURLEX] POST 2.12s status=200 bytes=996770
[EURLEX] page=11 numhits=50 hits_parsed=38 missing_celex=12
[EURLEX] POST 1.91s status=200 bytes=1165714
[EURLEX] page=12 numhits=50 hits_parsed=38 missing_celex=12
[EURLEX] POST 1.75s status=200 bytes=1262849
[EURLEX] page=13 numhits=50 hits_parsed=37 missing_celex=13
[EURLEX] POST 2.45s status=200 bytes=1087498
[EURLEX] page=14 numhits=50 hits_parsed=33 missing_celex=17
[EURLEX] POST 3.67s status=200 bytes=1100313
[EURLEX] page=15 numhits=50 hits_parsed=30 missing_celex=20
[EURLEX] POST 2.30s status=200 bytes=1093616
[EURLEX] page=16 numhits=50 hits_parsed=21 missing_celex=29
[EURLEX] POST 2.85s status=200 bytes=1053170
[EURLEX] page=17 numhits=50 hits_parsed=26 missing_celex=24
[EURLEX] POST 3.21s status=200 bytes=1209168
[EURLEX] page=18 numhits=50 hits_parsed=39 missing_celex=11
[EURLEX] POST 2.12s status=200 bytes=1164018
[EURLEX] page=19 numhits=50 hits_parsed=32 missing_celex=18
[EURLEX] POST 2.66s status=200 bytes=1236875
[EURLEX] page=20 numhits=50 hits_parsed=36 missing_celex=14
[EURLEX] POST 3.77s status=200 bytes=1262094
[EURLEX] page=21 numhits=50 hits_parsed=33 missing_celex=17
[EURLEX] POST 3.03s status=200 bytes=1157091

## Inspect retrieved CELEX hits

In [6]:
if retrieval_mode == "live_webservice" and live_rows:
    all_eu_rows_df = pd.DataFrame(live_rows)
elif ALLOW_FALLBACK and CACHED_ROWS.exists():
    print("Using retrieval-output fallback:", CACHED_ROWS)
    all_eu_rows_df = load_cached_eu_rows(CACHED_ROWS)
elif ALLOW_FALLBACK:
    print("Using last-resort corpus reconstruction fallback from all_docs_df.csv")
    fallback_terms = SEARCH_TERMS + [term for terms in TRANSLATED_TERMS.values() for term in terms]
    all_eu_rows_df = reconstruct_eu_rows_from_corpus(CANONICAL_ALL_DOCS, fallback_terms)
else:
    raise RuntimeError("No retrieval rows available and fallback disabled.")

preview_df("all_eu_rows_df", all_eu_rows_df)
if not all_eu_rows_df.empty:
    display(all_eu_rows_df[["scope", "lang"]].value_counts().rename("rows").reset_index().head(20))
    display(all_eu_rows_df[["celex", "title", "term_group"]].head(10))

all_eu_rows_df: shape=(20122, 8)

,source,scope,lang,term_group,title,celex,date,url
0,EU,ALL_ALL,en,nature-positive | nature positive | nature inclusive | nature-inclusive | nature-inclusive | nature inclusive design | nature based solutions | nature-based solutions | biodiversity net gain | biodiversity net-gain |...,Opinion of the European Committee of the Regions – Designing nature credits: A framework to promote biodiversity and ecosystem services,52025IR0140,2025-10-14,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52025IR0140
1,EU,ALL_ALL,en,nature-positive | nature positive | nature inclusive | nature-inclusive | nature-inclusive | nature inclusive design | nature based solutions | nature-based solutions | biodiversity net gain | biodiversity net-gain |...,"COMMUNICATION FROM THE COMMISSION TO THE EUROPEAN PARLIAMENT, THE COUNCIL, THE EUROPEAN ECONOMIC AND SOCIAL COMMITTEE AND THE COMMITTEE OF THE REGIONS Roadmap towards Nature Credits",52025DC0374,2025-07-07,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52025DC0374
2,EU,ALL_ALL,en,nature-positive | nature positive | nature inclusive | nature-inclusive | nature-inclusive | nature inclusive design | nature based solutions | nature-based solutions | biodiversity net gain | biodiversity net-gain |...,Commission NoticeTable of contents – Technical guidance on applying the do no significant harm principle under the Social Climate Fund Regulation,52025XC01596,2025-03-25,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52025XC01596
3,EU,ALL_ALL,en,nature-positive | nature positive | nature inclusive | nature-inclusive | nature-inclusive | nature inclusive design | nature based solutions | nature-based solutions | biodiversity net gain | biodiversity net-gain |...,P9_TA(2023)0277 – Nature restoration – Amendments adopted by the European Parliament on 12 July 2023 on the proposal for a regulation of the European Parliament and of the Council on nature restoration (COM(2022)0304...,52023AP0277,2023-07-12,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52023AP0277
4,EU,ALL_ALL,en,nature-positive | nature positive | nature inclusive | nature-inclusive | nature-inclusive | nature inclusive design | nature based solutions | nature-based solutions | biodiversity net gain | biodiversity net-gain |...,Proposal for a REGULATION OF THE EUROPEAN PARLIAMENT AND OF THE COUNCIL on nature restoration,52022PC0304,2022-06-22,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52022PC0304

      scope lang  rows
0   ALL_ALL   en  3878
1   ALL_ALL   de  1186
2   ALL_ALL   it  1169
3   ALL_ALL   es  1166
4   ALL_ALL   nl  1108
5   ALL_ALL   pt  1093
6   ALL_ALL   da  1059
7   ALL_ALL   fr  1013
8   ALL_ALL   mt   865
9   ALL_ALL   el   807
10  ALL_ALL   bg   768
11  ALL_ALL   cs   678
12  ALL_ALL   ro   610
13  ALL_ALL   et   601
14  ALL_ALL   lt   558
15  ALL_ALL   fi   534
16  ALL_ALL   sv   526
17  ALL_ALL   pl   442
18  ALL_ALL   sk   413
19  ALL_ALL   sl   406

,celex,title,term_group
0,52025IR0140,Opinion of the European Committee of the Regions – Designing nature credits: A framework to promote biodiversity and ecosystem services,nature-positive | nature positive | nature inclusive | nature-inclusive | nature-inclusive | nature inclusive design | nature based solutions | nature-based solutions | biodiversity net gain | biodiversity net-gain |...
1,52025DC0374,"COMMUNICATION FROM THE COMMISSION TO THE EUROPEAN PARLIAMENT, THE COUNCIL, THE EUROPEAN ECONOMIC AND SOCIAL COMMITTEE AND THE COMMITTEE OF THE REGIONS Roadmap towards Nature Credits",nature-positive | nature positive | nature inclusive | nature-inclusive | nature-inclusive | nature inclusive design | nature based solutions | nature-based solutions | biodiversity net gain | biodiversity net-gain |...
2,52025XC01596,Commission NoticeTable of contents – Technical guidance on applying the do no significant harm principle under the Social Climate Fund Regulation,nature-positive | nature positive | nature inclusive | nature-inclusive | nature-inclusive | nature inclusive design | nature based solutions | nature-based solutions | biodiversity net gain | biodiversity net-gain |...
3,52023AP0277,P9_TA(2023)0277 – Nature restoration – Amendments adopted by the European Parliament on 12 July 2023 on the proposal for a regulation of the European Parliament and of the Council on nature restoration (COM(2022)0304...,nature-positive | nature positive | nature inclusive | nature-inclusive | nature-inclusive | nature inclusive design | nature based solutions | nature-based solutions | biodiversity net gain | biodiversity net-gain |...
4,52022PC0304,Proposal for a REGULATION OF THE EUROPEAN PARLIAMENT AND OF THE COUNCIL on nature restoration,nature-positive | nature positive | nature inclusive | nature-inclusive | nature-inclusive | nature inclusive design | nature based solutions | nature-based solutions | biodiversity net gain | biodiversity net-gain |...
5,52024AP0089,P9_TA(2024)0089 – Nature restoration – European Parliament legislative resolution of 27 February 2024 on the proposal for a regulation of the European Parliament and of the Council on nature restoration (COM(2022)030...,nature-positive | nature positive | nature inclusive | nature-inclusive | nature-inclusive | nature inclusive design | nature based solutions | nature-based solutions | biodiversity net gain | biodiversity net-gain |...
6,52022SC0167,COMMISSION STAFF WORKING DOCUMENT IMPACT ASSESSMENT Accompanying the proposal for a Regulation of the European Parliament and of the Council on nature restoration,nature-positive | nature positive | nature inclusive | nature-inclusive | nature-inclusive | nature inclusive design | nature based solutions | nature-based solutions | biodiversity net gain | biodiversity net-gain |...
7,32024R1991,Regulation (EU) 2024/1991 of the European Parliament and of the Council of 24 June 2024 on nature restoration and amending Regulation (EU) 2022/869 (Text with EEA relevance),nature-positive | nature positive | nature inclusive | nature-inclusive | nature-inclusive | nature inclusive design | nature based solutions | nature-based solutions | biodiversity net gain | biodiversity net-gain |...
8,52024IE1184,Opinion of the European Economic and Social Committee – A comprehensive strategy for biodiversity at COP16: bringing all sectors together for a common goal (own-initiative opinion),nature-positive | nature positive | nature inclusive | nature-inclusive | nature-inclusive | nature inclusive design | nature based solutions | nature-based solutions | biodiversity net gain | biodiversity net-gain |...
9,52025IR1930,Opinion of the European Committee of the Regions – Climate adaptation in cities and regions: building the European Climate Adaptation Plan,nature-positive | nature positive | nature inclusive | nature-inclusive | nature-inclusive | nature inclusive design | nature based solutions | nature-based solutions | biodiversity net gain | biodiversity net-gain |...

## Build `all_eu_rows`, `df_raw`, and `df_docs`

In [7]:
all_eu_rows = all_eu_rows_df.to_dict(orient="records")
print("raw EU rows:", len(all_eu_rows))

df_raw, df_docs = build_eu_doc_tables(all_eu_rows_df)
preview_df("df_raw", df_raw)
preview_df("df_docs", df_docs)
print("unique EU docs:", len(df_docs))
print("unique CELEX full IDs:", int(df_docs["celex_full"].nunique()))
print("unique base CELEX IDs:", int(df_docs["celex"].nunique()))

raw EU rows: 20122
df_raw: shape=(20122, 12)

,source,scope,lang,term_group,title,celex,date,url,celex_full,celex_version,doc_key,url_fix
0,EU,ALL_ALL,en,nature-positive | nature positive | nature inclusive | nature-inclusive | nature-inclusive | nature inclusive design | nature based solutions | nature-based solutions | biodiversity net gain | biodiversity net-gain |...,Opinion of the European Committee of the Regions – Designing nature credits: A framework to promote biodiversity and ecosystem services,52025IR0140,2025-10-14,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52025IR0140,52025IR0140,,EU:52025IR0140,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52025IR0140
1,EU,ALL_ALL,en,nature-positive | nature positive | nature inclusive | nature-inclusive | nature-inclusive | nature inclusive design | nature based solutions | nature-based solutions | biodiversity net gain | biodiversity net-gain |...,"COMMUNICATION FROM THE COMMISSION TO THE EUROPEAN PARLIAMENT, THE COUNCIL, THE EUROPEAN ECONOMIC AND SOCIAL COMMITTEE AND THE COMMITTEE OF THE REGIONS Roadmap towards Nature Credits",52025DC0374,2025-07-07,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52025DC0374,52025DC0374,,EU:52025DC0374,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52025DC0374
2,EU,ALL_ALL,en,nature-positive | nature positive | nature inclusive | nature-inclusive | nature-inclusive | nature inclusive design | nature based solutions | nature-based solutions | biodiversity net gain | biodiversity net-gain |...,Commission NoticeTable of contents – Technical guidance on applying the do no significant harm principle under the Social Climate Fund Regulation,52025XC01596,2025-03-25,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52025XC01596,52025XC01596,,EU:52025XC01596,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52025XC01596
3,EU,ALL_ALL,en,nature-positive | nature positive | nature inclusive | nature-inclusive | nature-inclusive | nature inclusive design | nature based solutions | nature-based solutions | biodiversity net gain | biodiversity net-gain |...,P9_TA(2023)0277 – Nature restoration – Amendments adopted by the European Parliament on 12 July 2023 on the proposal for a regulation of the European Parliament and of the Council on nature restoration (COM(2022)0304...,52023AP0277,2023-07-12,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52023AP0277,52023AP0277,,EU:52023AP0277,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52023AP0277
4,EU,ALL_ALL,en,nature-positive | nature positive | nature inclusive | nature-inclusive | nature-inclusive | nature inclusive design | nature based solutions | nature-based solutions | biodiversity net gain | biodiversity net-gain |...,Proposal for a REGULATION OF THE EUROPEAN PARLIAMENT AND OF THE COUNCIL on nature restoration,52022PC0304,2022-06-22,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52022PC0304,52022PC0304,,EU:52022PC0304,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:52022PC0304

df_docs: shape=(2790, 12)

,doc_key,source,celex,celex_full,celex_version,url,url_fix,title,date,scopes,query_langs,query_term_groups
0,EU:01995A0805(01)-20131213,EU,01995A0805(01),01995A0805(01)-20131213,20131213,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01995A0805(01)-20131213,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01995A0805(01)-20131213,"Convenzione sulla protezione e l’utilizzazione dei corsi d’acqua transfrontalieri e dei laghi internazionali in data, a Helsinki, il 17 marzo 1992 Nazioni unite 1992 Convenzione sulla protezione e l’utilizzazione dei...",2013-12-13,"[""ALL_ALL""]","[""de"", ""et"", ""it""]","[""loodusega arvestav disain | looduspositiivne | looduspõhised lahendused | looduspõhine lahendus | elurikkuse strateegia | ELi elurikkuse strateegia | looduse taastamine | ökosüsteemide taastamine"", ""naturverträglic..."
1,EU:01996A0312(01)-20130925,EU,01996A0312(01),01996A0312(01)-20130925,20130925,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996A0312(01)-20130925,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996A0312(01)-20130925,Convention sur la protection des Alpes (convention alpine),2013-09-25,"[""ALL_ALL""]","[""el"", ""fr""]","[""aménagement respectueux de la nature | positif pour la nature | solutions fondées sur la nature | solution fondée sur la nature | gain net | gain net pour la biodiversité | stratégie pour la biodiversité | stratégi..."
2,EU:01996L0061-20060224,EU,01996L0061,01996L0061-20060224,20060224,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996L0061-20060224,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996L0061-20060224,Директива 96/61/ЕО на Съвета от 24 септември 1996 година за комплексно предотвратяване и контрол на замърсяването,2006-02-24,"[""ALL_ALL""]","[""bg""]","[""интегриран с природата дизайн | природосъобразен дизайн | природопозитивен | природосъобразни решения | стратегия за биологичното разнообразие | стратегия на ЕС за биологичното разнообразие | възстановяване на прир..."
3,EU:02002D0011(01)-20051118,EU,02002D0011(01),02002D0011(01)-20051118,20051118,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20051118,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20051118,Décision de la Banque centrale européenne du 5 décembre 2002 concernant les comptes annuels de la Banque centrale européenne (BCE/2002/11) (2003/132/CE),2005-11-18,"[""ALL_ALL""]","[""es"", ""fr""]","[""aménagement respectueux de la nature | positif pour la nature | solutions fondées sur la nature | solution fondée sur la nature | gain net | gain net pour la biodiversité | stratégie pour la biodiversité | stratégi..."
4,EU:02002D0011(01)-20060313,EU,02002D0011(01),02002D0011(01)-20060313,20060313,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20060313,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20060313,Décision de la Banque centrale européenne du 5 décembre 2002 concernant les comptes annuels de la Banque centrale européenne (BCE/2002/11) (2003/132/CE),2006-03-13,"[""ALL_ALL""]","[""es"", ""fr""]","[""aménagement respectueux de la nature | positif pour la nature | solutions fondées sur la nature | solution fondée sur la nature | gain net | gain net pour la biodiversité | stratégie pour la biodiversité | stratégi..."

unique EU docs: 2790
unique CELEX full IDs: 2790
unique base CELEX IDs: 2628

## Deduplicate CELEX list for full-text retrieval

In [13]:
fulltext_index_df = df_docs[["doc_key", "celex_full", "celex", "celex_version", "title", "url", "url_fix", "query_langs"]].drop_duplicates(subset=["celex_full"]).copy()
fulltext_index_df = annotate_celex_types(fulltext_index_df, celex_col="celex_full")
preview_df("fulltext_index_df", fulltext_index_df)
print("CELEX documents queued before filtering:", len(fulltext_index_df))

celex_sector_counts_df = fulltext_index_df["celex_sector"].fillna("").astype(str).value_counts(dropna=False).rename_axis("celex_sector").reset_index(name="rows")
preview_df("celex_sector_counts_df", celex_sector_counts_df)

celex_descriptor_counts_df = fulltext_index_df["celex_descriptor"].fillna("").astype(str).value_counts(dropna=False).rename_axis("celex_descriptor").reset_index(name="rows")
preview_df("celex_descriptor_counts_df", celex_descriptor_counts_df)

celex_class_counts_df = fulltext_index_df["celex_class"].fillna("").astype(str).value_counts(dropna=False).rename_axis("celex_class").reset_index(name="rows")
preview_df("celex_class_counts_df", celex_class_counts_df)

nonstandard_celex_examples_df = fulltext_index_df[
    ~fulltext_index_df["celex_sector"].fillna("").astype(str).isin(["3"])
][[
    "celex_full", "celex_sector", "celex_sector_label", "celex_descriptor", "celex_descriptor_label", "celex_class", "title"
]].copy()
preview_df("nonstandard_celex_examples_df", nonstandard_celex_examples_df)

fulltext_index_filtered_df = filter_celex_types_for_fulltext(
    fulltext_index_df,
    mode=FULLTEXT_CELEX_FILTER_MODE,
    exclude_descriptors=FULLTEXT_EXCLUDE_DESCRIPTORS,
)
preview_df("fulltext_index_filtered_df", fulltext_index_filtered_df)
print("FULLTEXT_CELEX_FILTER_MODE =", FULLTEXT_CELEX_FILTER_MODE)
print("FULLTEXT_EXCLUDE_DESCRIPTORS =", FULLTEXT_EXCLUDE_DESCRIPTORS)
print("CELEX documents queued after filtering:", len(fulltext_index_filtered_df))

write_csv(fulltext_index_filtered_df, FULLTEXT_INDEX_OUT)

fulltext_index_df: shape=(2790, 18)

,doc_key,celex_full,celex,celex_version,title,url,url_fix,query_langs,celex_valid,celex_sector,celex_sector_label,celex_descriptor,celex_descriptor_label,celex_notes,celex_is_corrigendum,celex_is_consolidated,celex_class,fulltext_support
0,EU:01995A0805(01)-20131213,01995A0805(01)-20131213,01995A0805(01),20131213,"Convenzione sulla protezione e l’utilizzazione dei corsi d’acqua transfrontalieri e dei laghi internazionali in data, a Helsinki, il 17 marzo 1992 Nazioni unite 1992 Convenzione sulla protezione e l’utilizzazione dei...",https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01995A0805(01)-20131213,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01995A0805(01)-20131213,"[""de"", ""et"", ""it""]",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported
1,EU:01996A0312(01)-20130925,01996A0312(01)-20130925,01996A0312(01),20130925,Convention sur la protection des Alpes (convention alpine),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996A0312(01)-20130925,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996A0312(01)-20130925,"[""el"", ""fr""]",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported
2,EU:01996L0061-20060224,01996L0061-20060224,01996L0061,20060224,Директива 96/61/ЕО на Съвета от 24 септември 1996 година за комплексно предотвратяване и контрол на замърсяването,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996L0061-20060224,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996L0061-20060224,"[""bg""]",True,0,Consolidated texts,L,Directive,,False,True,sector_0_consolidated,supported
3,EU:02002D0011(01)-20051118,02002D0011(01)-20051118,02002D0011(01),20051118,Décision de la Banque centrale européenne du 5 décembre 2002 concernant les comptes annuels de la Banque centrale européenne (BCE/2002/11) (2003/132/CE),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20051118,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20051118,"[""es"", ""fr""]",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported
4,EU:02002D0011(01)-20060313,02002D0011(01)-20060313,02002D0011(01),20060313,Décision de la Banque centrale européenne du 5 décembre 2002 concernant les comptes annuels de la Banque centrale européenne (BCE/2002/11) (2003/132/CE),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20060313,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20060313,"[""es"", ""fr""]",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported

CELEX documents queued before filtering: 2790
celex_sector_counts_df: shape=(8, 2)

  celex_sector  rows
0            5  1865
1                394
2            3   235
3            0   207
4            9    41

celex_descriptor_counts_df: shape=(35, 2)

  celex_descriptor  rows
0               SC   670
1                    394
2               DC   386
3               PC   315
4                R   278

celex_class_counts_df: shape=(8, 2)

             celex_class  rows
0   sector_5_preparatory  1865
1     unknown_or_invalid   394
2    sector_3_legal_acts   235
3  sector_0_consolidated   207
4         sector_9_other    41

nonstandard_celex_examples_df: shape=(2555, 7)

,celex_full,celex_sector,celex_sector_label,celex_descriptor,celex_descriptor_label,celex_class,title
0,01995A0805(01)-20131213,,,,,unknown_or_invalid,"Convenzione sulla protezione e l’utilizzazione dei corsi d’acqua transfrontalieri e dei laghi internazionali in data, a Helsinki, il 17 marzo 1992 Nazioni unite 1992 Convenzione sulla protezione e l’utilizzazione dei..."
1,01996A0312(01)-20130925,,,,,unknown_or_invalid,Convention sur la protection des Alpes (convention alpine)
2,01996L0061-20060224,0,Consolidated texts,L,Directive,sector_0_consolidated,Директива 96/61/ЕО на Съвета от 24 септември 1996 година за комплексно предотвратяване и контрол на замърсяването
3,02002D0011(01)-20051118,,,,,unknown_or_invalid,Décision de la Banque centrale européenne du 5 décembre 2002 concernant les comptes annuels de la Banque centrale européenne (BCE/2002/11) (2003/132/CE)
4,02002D0011(01)-20060313,,,,,unknown_or_invalid,Décision de la Banque centrale européenne du 5 décembre 2002 concernant les comptes annuels de la Banque centrale européenne (BCE/2002/11) (2003/132/CE)

fulltext_index_filtered_df: shape=(2790, 18)

,doc_key,celex_full,celex,celex_version,title,url,url_fix,query_langs,celex_valid,celex_sector,celex_sector_label,celex_descriptor,celex_descriptor_label,celex_notes,celex_is_corrigendum,celex_is_consolidated,celex_class,fulltext_support
0,EU:01995A0805(01)-20131213,01995A0805(01)-20131213,01995A0805(01),20131213,"Convenzione sulla protezione e l’utilizzazione dei corsi d’acqua transfrontalieri e dei laghi internazionali in data, a Helsinki, il 17 marzo 1992 Nazioni unite 1992 Convenzione sulla protezione e l’utilizzazione dei...",https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01995A0805(01)-20131213,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01995A0805(01)-20131213,"[""de"", ""et"", ""it""]",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported
1,EU:01996A0312(01)-20130925,01996A0312(01)-20130925,01996A0312(01),20130925,Convention sur la protection des Alpes (convention alpine),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996A0312(01)-20130925,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996A0312(01)-20130925,"[""el"", ""fr""]",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported
2,EU:01996L0061-20060224,01996L0061-20060224,01996L0061,20060224,Директива 96/61/ЕО на Съвета от 24 септември 1996 година за комплексно предотвратяване и контрол на замърсяването,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996L0061-20060224,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996L0061-20060224,"[""bg""]",True,0,Consolidated texts,L,Directive,,False,True,sector_0_consolidated,supported
3,EU:02002D0011(01)-20051118,02002D0011(01)-20051118,02002D0011(01),20051118,Décision de la Banque centrale européenne du 5 décembre 2002 concernant les comptes annuels de la Banque centrale européenne (BCE/2002/11) (2003/132/CE),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20051118,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20051118,"[""es"", ""fr""]",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported
4,EU:02002D0011(01)-20060313,02002D0011(01)-20060313,02002D0011(01),20060313,Décision de la Banque centrale européenne du 5 décembre 2002 concernant les comptes annuels de la Banque centrale européenne (BCE/2002/11) (2003/132/CE),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20060313,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20060313,"[""es"", ""fr""]",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported

FULLTEXT_CELEX_FILTER_MODE = all
FULLTEXT_EXCLUDE_DESCRIPTORS = []
CELEX documents queued after filtering: 2790
Wrote: c:\Users\acali\OneDrive - Danmarks Tekniske Universitet\PostDoc\Code\NiD-Policy-Analysis\analysis_pipeline\outputs\eurlex_all_fulltext_index.csv
Shape: (2790, 18)

,doc_key,celex_full,celex,celex_version,title,url,url_fix,query_langs,celex_valid,celex_sector,celex_sector_label,celex_descriptor,celex_descriptor_label,celex_notes,celex_is_corrigendum,celex_is_consolidated,celex_class,fulltext_support
0,EU:01995A0805(01)-20131213,01995A0805(01)-20131213,01995A0805(01),20131213,"Convenzione sulla protezione e l’utilizzazione dei corsi d’acqua transfrontalieri e dei laghi internazionali in data, a Helsinki, il 17 marzo 1992 Nazioni unite 1992 Convenzione sulla protezione e l’utilizzazione dei...",https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01995A0805(01)-20131213,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01995A0805(01)-20131213,"[""de"", ""et"", ""it""]",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported
1,EU:01996A0312(01)-20130925,01996A0312(01)-20130925,01996A0312(01),20130925,Convention sur la protection des Alpes (convention alpine),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996A0312(01)-20130925,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996A0312(01)-20130925,"[""el"", ""fr""]",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported
2,EU:01996L0061-20060224,01996L0061-20060224,01996L0061,20060224,Директива 96/61/ЕО на Съвета от 24 септември 1996 година за комплексно предотвратяване и контрол на замърсяването,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996L0061-20060224,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996L0061-20060224,"[""bg""]",True,0,Consolidated texts,L,Directive,,False,True,sector_0_consolidated,supported
3,EU:02002D0011(01)-20051118,02002D0011(01)-20051118,02002D0011(01),20051118,Décision de la Banque centrale européenne du 5 décembre 2002 concernant les comptes annuels de la Banque centrale européenne (BCE/2002/11) (2003/132/CE),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20051118,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20051118,"[""es"", ""fr""]",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported
4,EU:02002D0011(01)-20060313,02002D0011(01)-20060313,02002D0011(01),20060313,Décision de la Banque centrale européenne du 5 décembre 2002 concernant les comptes annuels de la Banque centrale européenne (BCE/2002/11) (2003/132/CE),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20060313,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20060313,"[""es"", ""fr""]",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported

# Full-text retrieval

## Batch full-text retrieval

This is the primary ordinary-EU full-text stage. It now follows the simpler old working logic from `NID_Retrieval_Pipeline_EURLEX_NIM.ipynb` for EU CELEX documents:

1. derive language candidates with EN first and then `query_langs`
2. derive CELEX variants: original CELEX, then base CELEX if consolidated
3. fetch from the Cellar CELEX URL using the old Accept / Accept-Language / Accept-Max-Cs-Size headers
4. parse returned HTML/XHTML into text
5. accept the first text above the minimal threshold and cache it

`legal-content` / `LexUriServ` are not the main ordinary-EU route here anymore; they remain part of the separate NIM pipeline.

In [14]:
fulltext_index_df = pd.read_csv(FULLTEXT_INDEX_OUT)
fulltext_index_df = annotate_celex_types(fulltext_index_df, celex_col="celex_full")
preview_df("fulltext_index_df (reloaded)", fulltext_index_df)

fulltext_cache_diag_df, fulltext_cache_compare_df, fulltext_cache_files_df = fulltext_cache_validation_diagnostics(
    FULLTEXT_CACHE_DIR,
    success_min_chars=FULLTEXT_SUCCESS_MIN_CHARS,
)
display(fulltext_cache_diag_df)
preview_df("fulltext_cache_compare_df", fulltext_cache_compare_df)

fulltext_cache_state_df, fulltext_cache_df = summarize_fulltext_cache_state(
    FULLTEXT_CACHE_DIR,
    fulltext_index_df,
    success_min_chars=FULLTEXT_SUCCESS_MIN_CHARS,
)
fulltext_cache_state_df = annotate_celex_types(fulltext_cache_state_df, celex_col="celex_full")
preview_df("fulltext_cache_state_df", fulltext_cache_state_df)
display(
    pd.DataFrame(
        [
            {"metric": "total_input_celex", "value": int(fulltext_index_df["celex_full"].astype(str).nunique())},
            {"metric": "already_successful", "value": int(fulltext_cache_state_df["cache_state"].eq("successful").sum())},
            {"metric": "previously_failed", "value": int(fulltext_cache_state_df["cache_state"].eq("failed").sum())},
            {"metric": "still_pending", "value": int(fulltext_cache_state_df["cache_state"].eq("pending").sum())},
        ]
    )
)

failed_cache_df = load_failed_fulltext_attempts(
    FULLTEXT_CACHE_DIR,
    success_min_chars=FULLTEXT_SUCCESS_MIN_CHARS,
)
failed_cache_df = annotate_celex_types(failed_cache_df, celex_col="celex_full") if not failed_cache_df.empty else failed_cache_df
preview_df("failed_cache_df", failed_cache_df)

successful_celex = set(fulltext_cache_state_df.loc[fulltext_cache_state_df["cache_state"].eq("successful"), "celex_full"].astype(str))
failed_celex = set(fulltext_cache_state_df.loc[fulltext_cache_state_df["cache_state"].eq("failed"), "celex_full"].astype(str))
next_run_df = fulltext_index_df.copy()
if FULLTEXT_RESUME:
    next_run_df = next_run_df.loc[~next_run_df["celex_full"].astype(str).isin(successful_celex)].copy()
    if not FULLTEXT_RETRY_FAILURES:
        next_run_df = next_run_df.loc[~next_run_df["celex_full"].astype(str).isin(failed_celex)].copy()
preview_df("next_run_df", next_run_df)
print("Resume enabled:", FULLTEXT_RESUME)
print("Retry failures:", FULLTEXT_RETRY_FAILURES)
print("CELEX queued for next run:", len(next_run_df))

fulltext_index_df (reloaded): shape=(2790, 18)

,doc_key,celex_full,celex,celex_version,title,url,url_fix,query_langs,celex_valid,celex_sector,celex_sector_label,celex_descriptor,celex_descriptor_label,celex_notes,celex_is_corrigendum,celex_is_consolidated,celex_class,fulltext_support
0,EU:01995A0805(01)-20131213,01995A0805(01)-20131213,01995A0805(01),20131213,"Convenzione sulla protezione e l’utilizzazione dei corsi d’acqua transfrontalieri e dei laghi internazionali in data, a Helsinki, il 17 marzo 1992 Nazioni unite 1992 Convenzione sulla protezione e l’utilizzazione dei...",https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01995A0805(01)-20131213,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01995A0805(01)-20131213,"[""de"", ""et"", ""it""]",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported
1,EU:01996A0312(01)-20130925,01996A0312(01)-20130925,01996A0312(01),20130925,Convention sur la protection des Alpes (convention alpine),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996A0312(01)-20130925,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996A0312(01)-20130925,"[""el"", ""fr""]",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported
2,EU:01996L0061-20060224,01996L0061-20060224,01996L0061,20060224,Директива 96/61/ЕО на Съвета от 24 септември 1996 година за комплексно предотвратяване и контрол на замърсяването,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996L0061-20060224,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996L0061-20060224,"[""bg""]",True,0,Consolidated texts,L,Directive,,False,True,sector_0_consolidated,supported
3,EU:02002D0011(01)-20051118,02002D0011(01)-20051118,02002D0011(01),20051118,Décision de la Banque centrale européenne du 5 décembre 2002 concernant les comptes annuels de la Banque centrale européenne (BCE/2002/11) (2003/132/CE),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20051118,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20051118,"[""es"", ""fr""]",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported
4,EU:02002D0011(01)-20060313,02002D0011(01)-20060313,02002D0011(01),20060313,Décision de la Banque centrale européenne du 5 décembre 2002 concernant les comptes annuels de la Banque centrale européenne (BCE/2002/11) (2003/132/CE),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20060313,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20060313,"[""es"", ""fr""]",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported

                        metric  value
0               cache_csv_rows    149
1         cache_csv_status_200      0
2  cache_csv_text_ge_threshold      0
3           existing_txt_files     16
4       txt_files_ge_threshold     16
5  csv_vs_file_inconsistencies     16

fulltext_cache_compare_df: shape=(100, 15)

,celex_full,celex,celex_version,lang,retrieval_status,retrieval_error,text_len,source_url,timestamp,file_text_len,text_path,file_exists,csv_success,file_success,inconsistent_csv_vs_files
0,01995A0805(01)-20131213,01995A0805(01),20131213,it,202,route_exhausted_after_202,0,https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=CELEX%3A01995A0805%2801%29%3AIT%3AHTML,2026-04-08T07:51:23.314432+00:00,0,NaN,NaN,False,False,False
1,01996A0312(01)-20130925,01996A0312(01),20130925,fr,202,route_exhausted_after_202,0,https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=CELEX%3A01996A0312%2801%29%3AFR%3AHTML,2026-04-08T07:51:23.314432+00:00,0,NaN,NaN,False,False,False
2,01996L0061-20060224,01996L0061,20060224,bg,202,route_exhausted_after_202,0,https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=CELEX%3A01996L0061%3ABG%3AHTML,2026-04-08T07:51:23.314432+00:00,59271,c:\Users\acali\OneDrive - Danmarks Tekniske Universitet\PostDoc\Code\NiD-Policy-Analysis\analysis_pipeline\outputs\eurlex_all_fulltext_cache\text_cache\01996L0061-20060224.txt,True,False,True,True
3,02002D0011(01)-20051118,02002D0011(01),20051118,fr,202,route_exhausted_after_202,0,https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=CELEX%3A02002D0011%2801%29%3AFR%3AHTML,2026-04-08T07:51:23.314432+00:00,0,NaN,NaN,False,False,False
4,02002D0011(01)-20060313,02002D0011(01),20060313,fr,202,route_exhausted_after_202,0,https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=CELEX%3A02002D0011%2801%29%3AFR%3AHTML,2026-04-08T07:51:23.314432+00:00,0,NaN,NaN,False,False,False

fulltext_cache_state_df: shape=(2790, 23)

,celex_full,celex,celex_version,lang,retrieval_status,retrieval_error,text_len,source_url,timestamp,file_text_len,text_path,file_exists,cache_state,celex_valid,celex_sector,celex_sector_label,celex_descriptor,celex_descriptor_label,celex_notes,celex_is_corrigendum,celex_is_consolidated,celex_class,fulltext_support
0,01995A0805(01)-20131213,01995A0805(01),20131213,it,202,route_exhausted_after_202,0,https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=CELEX%3A01995A0805%2801%29%3AIT%3AHTML,2026-04-08T07:51:23.314432+00:00,0,,False,failed,False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported
1,01996A0312(01)-20130925,01996A0312(01),20130925,fr,202,route_exhausted_after_202,0,https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=CELEX%3A01996A0312%2801%29%3AFR%3AHTML,2026-04-08T07:51:23.314432+00:00,0,,False,failed,False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported
2,01996L0061-20060224,01996L0061,20060224,bg,202,route_exhausted_after_202,0,https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=CELEX%3A01996L0061%3ABG%3AHTML,2026-04-08T07:51:23.314432+00:00,59271,c:\Users\acali\OneDrive - Danmarks Tekniske Universitet\PostDoc\Code\NiD-Policy-Analysis\analysis_pipeline\outputs\eurlex_all_fulltext_cache\text_cache\01996L0061-20060224.txt,True,successful,True,0,Consolidated texts,L,Directive,,False,True,sector_0_consolidated,supported
3,02002D0011(01)-20051118,02002D0011(01),20051118,fr,202,route_exhausted_after_202,0,https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=CELEX%3A02002D0011%2801%29%3AFR%3AHTML,2026-04-08T07:51:23.314432+00:00,0,,False,failed,False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported
4,02002D0011(01)-20060313,02002D0011(01),20060313,fr,202,route_exhausted_after_202,0,https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=CELEX%3A02002D0011%2801%29%3AFR%3AHTML,2026-04-08T07:51:23.314432+00:00,0,,False,failed,False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported

               metric  value
0   total_input_celex   2790
1  already_successful     16
2   previously_failed     84
3       still_pending   2690

failed_cache_df: shape=(149, 20)

,celex_full,celex,celex_version,lang,text,source_url,retrieval_status,retrieval_error,text_len,timestamp,celex_valid,celex_sector,celex_sector_label,celex_descriptor,celex_descriptor_label,celex_notes,celex_is_corrigendum,celex_is_consolidated,celex_class,fulltext_support
0,01995A0805(01)-20131213,01995A0805(01),20131213,en,,,0,unsupported_celex_type_for_fulltext,0,2026-04-07T13:16:44.506784+00:00,False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported
1,01996A0312(01)-20130925,01996A0312(01),20130925,en,,,0,unsupported_celex_type_for_fulltext,0,2026-04-07T13:16:44.506784+00:00,False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported
2,01996L0061-20060224,01996L0061,20060224,en,,https://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=CELEX%3A01996L0061%3ABG%3AHTML,202,HTTP 202,0,2026-04-07T13:16:44.506784+00:00,True,0,Consolidated texts,L,Directive,,False,True,sector_0_consolidated,supported
3,02002D0011(01)-20051118,02002D0011(01),20051118,en,,,0,unsupported_celex_type_for_fulltext,0,2026-04-07T13:16:44.506784+00:00,False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported
4,02002D0011(01)-20060313,02002D0011(01),20060313,en,,,0,unsupported_celex_type_for_fulltext,0,2026-04-07T13:16:44.506784+00:00,False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported

next_run_df: shape=(2774, 18)

,doc_key,celex_full,celex,celex_version,title,url,url_fix,query_langs,celex_valid,celex_sector,celex_sector_label,celex_descriptor,celex_descriptor_label,celex_notes,celex_is_corrigendum,celex_is_consolidated,celex_class,fulltext_support
0,EU:01995A0805(01)-20131213,01995A0805(01)-20131213,01995A0805(01),20131213,"Convenzione sulla protezione e l’utilizzazione dei corsi d’acqua transfrontalieri e dei laghi internazionali in data, a Helsinki, il 17 marzo 1992 Nazioni unite 1992 Convenzione sulla protezione e l’utilizzazione dei...",https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01995A0805(01)-20131213,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01995A0805(01)-20131213,"[""de"", ""et"", ""it""]",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported
1,EU:01996A0312(01)-20130925,01996A0312(01)-20130925,01996A0312(01),20130925,Convention sur la protection des Alpes (convention alpine),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996A0312(01)-20130925,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996A0312(01)-20130925,"[""el"", ""fr""]",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported
3,EU:02002D0011(01)-20051118,02002D0011(01)-20051118,02002D0011(01),20051118,Décision de la Banque centrale européenne du 5 décembre 2002 concernant les comptes annuels de la Banque centrale européenne (BCE/2002/11) (2003/132/CE),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20051118,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20051118,"[""es"", ""fr""]",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported
4,EU:02002D0011(01)-20060313,02002D0011(01)-20060313,02002D0011(01),20060313,Décision de la Banque centrale européenne du 5 décembre 2002 concernant les comptes annuels de la Banque centrale européenne (BCE/2002/11) (2003/132/CE),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20060313,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20060313,"[""es"", ""fr""]",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported
6,EU:02002O0010-20030101,02002O0010-20030101,02002O0010,20030101,Orientación del Banco Central Europeo de 5 de diciembre de 2002 sobre el régimen jurídico de la contabilidad y la elaboración de informes financieros en el sistema europeo de Bancos Centrales (BCE/2002/10) (2003/131/CE),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002O0010-20030101,https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002O0010-20030101,"[""es""]",True,0,Consolidated texts,O,Order / Oral question,,False,True,sector_0_consolidated,supported

Resume enabled: True
Retry failures: True
CELEX queued for next run: 2774

## Single-CELEX deep trace

Use this section to inspect the exact full-text decision path for a few CELEX values before running the batch job.

In [16]:
trace_summaries = []
trace_frames = []
trace_results = []
for trace_celex in FULLTEXT_TRACE_CELEX_LIST:
    trace_row = pd.Series({"celex_full": trace_celex, "celex": trace_celex, "lang": "en", "query_langs": "en"})
    trace_df, trace_result = trace_eurlex_fulltext_decision(
        trace_celex,
        cache_dir=FULLTEXT_CACHE_DIR,
        use_cache=False,
        timeout_s=FULLTEXT_TRACE_SINGLE_TIMEOUT_S,
        retries=max(1, min(FULLTEXT_RETRIES, 2)),
        min_interval_s=0.0,
    )
    trace_result = dict(trace_result)
    trace_result.pop("full_text_raw", None)
    trace_result.pop("full_text_clean", None)
    trace_results.append(trace_result)
    trace_summaries.append({
        "celex_full": trace_celex,
        "candidate_langs": ", ".join(lang_candidates_from_row(trace_row)),
        "celex_variants": ", ".join(celex_variants(trace_celex)),
        "cellar_url": cellar_celex_url(trace_celex),
        "final_url": trace_result.get("text_source_url", ""),
        "status": trace_result.get("retrieval_status", 0),
        "text_len": trace_result.get("text_len", 0),
        "retrieval_error": trace_result.get("retrieval_error", ""),
    })
    if not trace_df.empty:
        trace_frames.append(trace_df)

trace_summary_df = pd.DataFrame(trace_summaries)
trace_results_df = pd.DataFrame(trace_results)
trace_attempts_df = pd.concat(trace_frames, ignore_index=True) if trace_frames else pd.DataFrame()
preview_df("trace_summary_df", trace_summary_df)
preview_df("trace_results_df", trace_results_df)
preview_df("trace_attempts_df", trace_attempts_df)

[EURLEX TEXT] TRACE CELEX=01996L0061 variant=01996L0061 lang=EN route=cellar
[EURLEX TEXT] TRACE CELEX=02002D0272 variant=02002D0272 lang=EN route=cellar
[EURLEX TEXT] TRACE CELEX=02003L0087 variant=02003L0087 lang=EN route=cellar
trace_summary_df: shape=(3, 8)

,celex_full,candidate_langs,celex_variants,cellar_url,final_url,status,text_len,retrieval_error
0,01996L0061,en,01996L0061,http://publications.europa.eu/resource/celex/01996L0061,http://publications.europa.eu/resource/celex/01996L0061,404,0,HTTP 404
1,02002D0272,en,02002D0272,http://publications.europa.eu/resource/celex/02002D0272,http://publications.europa.eu/resource/celex/02002D0272,404,0,HTTP 404
2,02003L0087,en,02003L0087,http://publications.europa.eu/resource/celex/02003L0087,http://publications.europa.eu/resource/celex/02003L0087,404,0,HTTP 404

trace_results_df: shape=(3, 28)

,celex,celex_full,celex_version,title,url,text_source_url,text_len,retrieval_status,retrieval_error,lang,lang_source_fulltext,fetch_seconds,fetched_from_cache,text_path,celex_variant_used,route_used,content_type,attempt_trace,celex_valid,celex_sector,celex_sector_label,celex_descriptor,celex_descriptor_label,celex_notes,celex_is_corrigendum,celex_is_consolidated,celex_class,fulltext_support
0,01996L0061,01996L0061,,,,http://publications.europa.eu/resource/celex/01996L0061,0,404,HTTP 404,en,english_default,0.04,False,,01996L0061,cellar,,"[{'celex_full': '01996L0061', 'celex': '01996L0061', 'celex_variant': '01996L0061', 'lang': 'en', 'route_name': 'cellar', 'final_url': 'http://publications.europa.eu/resource/celex/01996L0061', 'status': 404, 'error'...",True,0,Consolidated texts,L,Directive,,False,True,sector_0_consolidated,supported
1,02002D0272,02002D0272,,,,http://publications.europa.eu/resource/celex/02002D0272,0,404,HTTP 404,en,english_default,0.04,False,,02002D0272,cellar,,"[{'celex_full': '02002D0272', 'celex': '02002D0272', 'celex_variant': '02002D0272', 'lang': 'en', 'route_name': 'cellar', 'final_url': 'http://publications.europa.eu/resource/celex/02002D0272', 'status': 404, 'error'...",True,0,Consolidated texts,D,Decision,,False,True,sector_0_consolidated,supported
2,02003L0087,02003L0087,,,,http://publications.europa.eu/resource/celex/02003L0087,0,404,HTTP 404,en,english_default,0.04,False,,02003L0087,cellar,,"[{'celex_full': '02003L0087', 'celex': '02003L0087', 'celex_variant': '02003L0087', 'lang': 'en', 'route_name': 'cellar', 'final_url': 'http://publications.europa.eu/resource/celex/02003L0087', 'status': 404, 'error'...",True,0,Consolidated texts,L,Directive,,False,True,sector_0_consolidated,supported

trace_attempts_df: shape=(3, 10)

,celex_full,celex,celex_variant,lang,route_name,final_url,status,error,content_type,text_len
0,01996L0061,01996L0061,01996L0061,en,cellar,http://publications.europa.eu/resource/celex/01996L0061,404,HTTP 404,,0
1,02002D0272,02002D0272,02002D0272,en,cellar,http://publications.europa.eu/resource/celex/02002D0272,404,HTTP 404,,0
2,02003L0087,02003L0087,02003L0087,en,cellar,http://publications.europa.eu/resource/celex/02003L0087,404,HTTP 404,,0

In [17]:
fulltext_live_df = pd.DataFrame()
fulltext_mode = "live_batch" if RUN_LIVE_FULLTEXT else "cached_fallback"
fulltext_live_error = ""

if RUN_LIVE_FULLTEXT:
    try:
        fulltext_live_df = batch_fetch_eurlex_fulltext(
            next_run_df,
            cache_dir=FULLTEXT_CACHE_DIR,
            use_cache=FULLTEXT_USE_CACHE,
            timeout_s=FULLTEXT_TIMEOUT_S,
            retries=FULLTEXT_RETRIES,
            min_interval_s=FULLTEXT_MIN_INTERVAL_S,
            max_docs=FULLTEXT_MAX_DOCS,
            verbose=FULLTEXT_VERBOSE,
            trace_routes=FULLTEXT_TRACE_ROUTES,
            resume=FULLTEXT_RESUME,
            retry_failures=FULLTEXT_RETRY_FAILURES,
            progress_every=FULLTEXT_PROGRESS_EVERY,
            cache_every=FULLTEXT_CACHE_EVERY,
            success_min_chars=FULLTEXT_SUCCESS_MIN_CHARS,
        )
    except Exception as exc:
        fulltext_live_error = str(exc)
        fulltext_mode = "cached_fallback" if ALLOW_FALLBACK else "live_failed"
        print("Live full-text retrieval failed.")
        print(fulltext_live_error)

print("fulltext_mode =", fulltext_mode)
preview_df("fulltext_live_df", fulltext_live_df)

=== EURLEX FULLTEXT RESUME STATE ===
Total input CELEX: 2774
Already successful: 0
Previously failed: 84
Still pending: 2690
Retry failures: True
Run set size: 2774
[EURLEX TEXT] 1/2774 CELEX=01995A0805(01) failed reason=404_not_found length=0
[EURLEX TEXT] 2/2774 CELEX=01996A0312(01) failed reason=404_not_found length=0
[EURLEX TEXT] 3/2774 CELEX=02002D0011(01) failed reason=404_not_found length=0
[EURLEX TEXT] 4/2774 CELEX=02002D0011(01) failed reason=404_not_found length=0
[EURLEX TEXT] 5/2774 CELEX=02002O0010 failed reason=sector0_route_mismatch length=0
[EURLEX TEXT] 5/2774 processed | success=0 | failed=5
[EURLEX TEXT] 6/2774 CELEX=02003R1725 success length=2156781
[EURLEX TEXT] 7/2774 CELEX=02003R1725 success length=2165833
[EURLEX TEXT] 8/2774 CELEX=02003R1725 success length=2179290
[EURLEX TEXT] 9/2774 CELEX=02003R1725 success length=2217797
[EURLEX TEXT] 10/2774 CELEX=02003R1725 success length=2223938
[EURLEX TEXT] 10/2774 processed | success=5 | failed=5
[EURLEX TEXT] 11/2774 CELEX=02004R0794 success length=1491583
[EURLEX TEXT] 12/2774 CELEX=02004R0794 success length=1492046
[EURLEX TEXT] 13/2774 CELEX=02006O0016 success length=101331
[EURLEX TEXT] 14/2774 CELEX=02006O0016 success length=104594
[EURLEX TEXT] 15/2774 CELEX=02006O0016 success length=106957
[EURLEX TEXT] 15/2774 processed | success=10 | failed=5
[EURLEX TEXT] 16/2774 CELEX=02006O0016 success length=109254
[EURLEX TEXT] 17/2774 CELEX=02007R0193 success length=96452
[EURLEX TEXT] 18/2774 CELEX=02008L0001 success length=64008
[EURLEX TEXT] 19/2774 CELEX=02008L0056 success length=56774
[EURLEX TEXT] 20/2774 CELEX=02008R1126 failed reason=sector0_route_mismatch length=0
[EURLEX TEXT] 20/2774 processed | success=14 | failed=6
[EURLEX TEXT] 21/2774 CELEX=02008R1126 failed reason=sector0_route_mismatch length=0
[EURLEX TEXT] 22/2774 CELEX=02008R1126 failed reason=sector0_route_mismatch length=0
[EURLEX TEXT] 23/2774 CELEX=02008R1126 failed reason=sector0_route_mismatch length=0
[EURLEX TEXT] 24/2774 CELEX=02008R1126 failed reason=sector0_route_mismatch length=0
[EURLEX TEXT] 25/2774 CELEX=02008R1126 failed reason=sector0_route_mismatch length=0
[EURLEX TEXT] 25/2774 processed | success=14 | failed=11
[EURLEX TEXT] 26/2774 CELEX=02008R1126 failed reason=sector0_route_mismatch length=0
[EURLEX TEXT] 27/2774 CELEX=02008R1126 success length=2120373
[EURLEX TEXT] 28/2774 CELEX=02008R1126 success length=2121759
[EURLEX TEXT] 29/2774 CELEX=02008R1126 success length=2239296
[EURLEX TEXT] 30/2774 CELEX=02008R1126 success length=2250088
[EURLEX TEXT] 30/2774 processed | success=18 | failed=12
[EURLEX TEXT] 31/2774 CELEX=02008R1126 success length=2429651
[EURLEX TEXT] 32/2774 CELEX=02008R1126 success length=2437410
[EURLEX TEXT] 33/2774 CELEX=02008R1126 success length=2441041
[EURLEX TEXT] 34/2774 CELEX=02008R1126 success length=2472437
[EURLEX TEXT] 35/2774 CELEX=02008R1126 success length=2480588
[EURLEX TEXT] 35/2774 processed | success=23 | failed=12
[EURLEX TEXT] 36/2774 CELEX=02008R1126 success length=2997685
[EURLEX TEXT] 37/2774 CELEX=02008R1126 success length=3125933
[EURLEX TEXT] 38/2774 CELEX=02008R1126 success length=3159456
[EURLEX TEXT] 39/2774 CELEX=02008R1126 success length=3162281
[EURLEX TEXT] 40/2774 CELEX=02008R1126 success length=3196060
[EURLEX TEXT] 40/2774 processed | success=28 | failed=12
[EURLEX TEXT] 41/2774 CELEX=02008R1126 success length=3197586
[EURLEX TEXT] 42/2774 CELEX=02008R1126 success length=2030096
[EURLEX TEXT] 43/2774 CELEX=02008R1126 success length=3395982
[EURLEX TEXT] 44/2774 CELEX=02009D0607 success length=43018
[EURLEX TEXT] 45/2774 CELEX=02009D0607 success length=40651
[EURLEX TEXT] 45/2774 processed | success=33 | failed=12
[EURLEX TEXT] 46/2774 CELEX=02009R1221 success length=147763
[EURLEX TEXT] 47/2774 CELEX=02009R1221 success length=148237
[EURLEX TEXT] 48/2774 CELEX=02010O0020 success length=124943
[EURLEX TEXT] 49/2774 CELEX=02010O0020 success length=113151
[EURLEX TEXT] 50/2774 CELEX=02010O0020 success length=113719
[EURLEX TEXT] 50/2774 processed | success=38 | failed=12
[EURLEX TEXT] cache saved -> eurlex_cache_fulltext.csv
[EURLEX TEXT] 50/2774 processed | success=38 | failed=12
[EURLEX TEXT] 51/2774 CELEX=02010O0020 success length=115315
[EURLEX TEXT] 52/2774 CELEX=02010O0020 success length=115691
[EURLEX TEXT] 53/2774 CELEX=02011L0016 success length=389390
[EURLEX TEXT] 54/2774 CELEX=02011R0405 success length=33401
[EURLEX TEXT] 55/2774 CELEX=02013D0743 success length=337854
[EURLEX TEXT] 55/2774 processed | success=43 | failed=12
[EURLEX TEXT] 56/2774 CELEX=02013R1291 success length=284010
[EURLEX TEXT] 57/2774 CELEX=02013R1293 success length=111741
[EURLEX TEXT] 58/2774 CELEX=02013R1293 success length=61457
[EURLEX TEXT] 59/2774 CELEX=02013R1293 success length=62586
[EURLEX TEXT] 60/2774 CELEX=02013R1305 success length=247027
[EURLEX TEXT] 60/2774 processed | success=48 | failed=12
[EURLEX TEXT] 61/2774 CELEX=02013R1305 success length=247125
[EURLEX TEXT] 62/2774 CELEX=02013R1305 success length=247507
[EURLEX TEXT] 63/2774 CELEX=02013R1305 success length=191921
[EURLEX TEXT] 64/2774 CELEX=02013R1305 success length=189674
[EURLEX TEXT] 65/2774 CELEX=02013R1305 success length=195863
[EURLEX TEXT] 65/2774 processed | success=53 | failed=12
[EURLEX TEXT] 66/2774 CELEX=02013R1305 success length=195933
[EURLEX TEXT] 67/2774 CELEX=02013R1305 success length=196050
[EURLEX TEXT] 68/2774 CELEX=02013R1305 success length=196634
[EURLEX TEXT] 69/2774 CELEX=02013R1305 success length=198663
[EURLEX TEXT] 70/2774 CELEX=02013R1305 success length=213945
[EURLEX TEXT] 70/2774 processed | success=58 | failed=12
[EURLEX TEXT] 71/2774 CELEX=02013R1305 success length=214472
[EURLEX TEXT] 72/2774 CELEX=02013R1305 success length=216967
[EURLEX TEXT] 73/2774 CELEX=02013R1308 success length=503941
[EURLEX TEXT] 74/2774 CELEX=02013R1308 success length=459739
[EURLEX TEXT] 75/2774 CELEX=02013R1308 success length=442625
[EURLEX TEXT] 75/2774 processed | success=63 | failed=12
[EURLEX TEXT] 76/2774 CELEX=02013R1308 success length=442876
[EURLEX TEXT] 77/2774 CELEX=02014A0520(02) failed reason=404_not_found length=0
[EURLEX TEXT] 78/2774 CELEX=02014A0830(01) failed reason=404_not_found length=0
[EURLEX TEXT] 79/2774 CELEX=02014A0830(01) failed reason=404_not_found length=0
[EURLEX TEXT] 80/2774 CELEX=02014A0830(01) failed reason=404_not_found length=0
[EURLEX TEXT] 80/2774 processed | success=64 | failed=16
[EURLEX TEXT] 81/2774 CELEX=02014A0830(01) failed reason=404_not_found length=0
[EURLEX TEXT] 82/2774 CELEX=02014A0830(01) failed reason=404_not_found length=0
[EURLEX TEXT] 83/2774 CELEX=02014A0830(01) failed reason=404_not_found length=0
[EURLEX TEXT] 84/2774 CELEX=02014A0830(01) failed reason=404_not_found length=0
[EURLEX TEXT] 85/2774 CELEX=02014A0830(01) failed reason=404_not_found length=0
[EURLEX TEXT] 85/2774 processed | success=64 | failed=21
[EURLEX TEXT] 86/2774 CELEX=02014A0830(01) failed reason=404_not_found length=0
[EURLEX TEXT] 87/2774 CELEX=02014A0830(02) failed reason=404_not_found length=0
[EURLEX TEXT] 88/2774 CELEX=02014A0830(02) failed reason=404_not_found length=0
[EURLEX TEXT] 89/2774 CELEX=02014A0830(02) failed reason=404_not_found length=0
[EURLEX TEXT] 90/2774 CELEX=02014A0830(02) failed reason=404_not_found length=0
[EURLEX TEXT] 90/2774 processed | success=64 | failed=26
[EURLEX TEXT] 91/2774 CELEX=02014A0830(02) failed reason=404_not_found length=0
[EURLEX TEXT] 92/2774 CELEX=02014A0830(02) failed reason=404_not_found length=0
[EURLEX TEXT] 93/2774 CELEX=02014A0830(02) failed reason=404_not_found length=0
[EURLEX TEXT] 94/2774 CELEX=02014A0830(02) failed reason=404_not_found length=0
[EURLEX TEXT] 95/2774 CELEX=02014A0830(02) failed reason=404_not_found length=0
[EURLEX TEXT] 95/2774 processed | success=64 | failed=31
[EURLEX TEXT] 96/2774 CELEX=02014A0830(02) failed reason=404_not_found length=0
[EURLEX TEXT] 97/2774 CELEX=02014A0830(02) failed reason=404_not_found length=0
[EURLEX TEXT] 98/2774 CELEX=02014R0215 success length=51584
[EURLEX TEXT] 99/2774 CELEX=02014R0215 success length=43664
[EURLEX TEXT] 100/2774 CELEX=02014R0215 success length=44013
[EURLEX TEXT] 100/2774 processed | success=67 | failed=33
[EURLEX TEXT] cache saved -> eurlex_cache_fulltext.csv
[EURLEX TEXT] 100/2774 processed | success=67 | failed=33
[EURLEX TEXT] 101/2774 CELEX=02014R0508 success length=180188
[EURLEX TEXT] 102/2774 CELEX=02014R0508 success length=180345
[EURLEX TEXT] 103/2774 CELEX=02014R0508 success length=181293
[EURLEX TEXT] 104/2774 CELEX=02014R0508 success length=181586
[EURLEX TEXT] 105/2774 CELEX=02014R0508 success length=185998
[EURLEX TEXT] 105/2774 processed | success=72 | failed=33
[EURLEX TEXT] 106/2774 CELEX=02014R0508 success length=188075
[EURLEX TEXT] 107/2774 CELEX=02014R0508 success length=190926
[EURLEX TEXT] 108/2774 CELEX=02014R0528 success length=23931
[EURLEX TEXT] 109/2774 CELEX=02014R0528 success length=18491
[EURLEX TEXT] 110/2774 CELEX=02014R0639 success length=170021
[EURLEX TEXT] 110/2774 processed | success=77 | failed=33
[EURLEX TEXT] 111/2774 CELEX=02014R0639 success length=176590
[EURLEX TEXT] 112/2774 CELEX=02014R0639 success length=143320
[EURLEX TEXT] 113/2774 CELEX=02014R0639 success length=143169
[EURLEX TEXT] 114/2774 CELEX=02014R0639 success length=145936
[EURLEX TEXT] 115/2774 CELEX=02014R0651 success length=342549
[EURLEX TEXT] 115/2774 processed | success=82 | failed=33
[EURLEX TEXT] 116/2774 CELEX=02014R0651 success length=342629
[EURLEX TEXT] 117/2774 CELEX=02014R0651 success length=469138
[EURLEX TEXT] 118/2774 CELEX=02014R0680 success length=1417938
[EURLEX TEXT] 119/2774 CELEX=02014R0680 success length=1414076
[EURLEX TEXT] 120/2774 CELEX=02014R0680 success length=1475699
[EURLEX TEXT] 120/2774 processed | success=87 | failed=33
[EURLEX TEXT] 121/2774 CELEX=02014R0680 success length=1444162
[EURLEX TEXT] 122/2774 CELEX=02014R0680 success length=1735483
[EURLEX TEXT] 123/2774 CELEX=02014R0680 success length=1780719
[EURLEX TEXT] 124/2774 CELEX=02014R0680 success length=1918250
[EURLEX TEXT] 125/2774 CELEX=02014R0680 success length=2037433
[EURLEX TEXT] 125/2774 processed | success=92 | failed=33
[EURLEX TEXT] 126/2774 CELEX=02014R0680 success length=2114196
[EURLEX TEXT] 127/2774 CELEX=02014R0680 success length=2410532
[EURLEX TEXT] 128/2774 CELEX=02014R0808 success length=140408
[EURLEX TEXT] 129/2774 CELEX=02014R0808 success length=140993
[EURLEX TEXT] 130/2774 CELEX=02014R0808 success length=140806
[EURLEX TEXT] 130/2774 processed | success=97 | failed=33
[EURLEX TEXT] 131/2774 CELEX=02014R0808 success length=140912
[EURLEX TEXT] 132/2774 CELEX=02014R0808 success length=141840
[EURLEX TEXT] 133/2774 CELEX=02014R0808 success length=145531
[EURLEX TEXT] 134/2774 CELEX=02014R0808 success length=146534
[EURLEX TEXT] 135/2774 CELEX=02014R1014 success length=17560
[EURLEX TEXT] 135/2774 processed | success=102 | failed=33
[EURLEX TEXT] 136/2774 CELEX=02014R1143 success length=61487
[EURLEX TEXT] 137/2774 CELEX=02014R1143 success length=58744
[EURLEX TEXT] 138/2774 CELEX=02014XC0701(01) failed reason=404_not_found length=0
[EURLEX TEXT] 139/2774 CELEX=02014XC0701(01) failed reason=404_not_found length=0
[EURLEX TEXT] 140/2774 CELEX=02014XC0701(01) failed reason=404_not_found length=0
[EURLEX TEXT] 140/2774 processed | success=104 | failed=36
[EURLEX TEXT] 141/2774 CELEX=02015D1158 success length=163410
[EURLEX TEXT] 142/2774 CELEX=02016O0034 success length=116961
[EURLEX TEXT] 143/2774 CELEX=02016O0034 success length=120580
[EURLEX TEXT] 144/2774 CELEX=02016O0034 success length=120619
[EURLEX TEXT] 145/2774 CELEX=02017R0653 success length=199773
[EURLEX TEXT] 145/2774 processed | success=109 | failed=36
[EURLEX TEXT] 146/2774 CELEX=02018D0813 success length=167371
[EURLEX TEXT] 147/2774 CELEX=02018R0841 success length=48098
[EURLEX TEXT] 148/2774 CELEX=02018R0841 success length=80304
[EURLEX TEXT] 149/2774 CELEX=02018R1999 success length=223583
[EURLEX TEXT] 150/2774 CELEX=02018R1999 success length=224115
[EURLEX TEXT] 150/2774 processed | success=114 | failed=36
[EURLEX TEXT] cache saved -> eurlex_cache_fulltext.csv
[EURLEX TEXT] 150/2774 processed | success=114 | failed=36
[EURLEX TEXT] 151/2774 CELEX=02019R0815 success length=1670396
[EURLEX TEXT] 152/2774 CELEX=02019R0815 success length=1860038
[EURLEX TEXT] 153/2774 CELEX=02019R0815 success length=1861770
[EURLEX TEXT] 154/2774 CELEX=02019R0815 success length=2279502
[EURLEX TEXT] 155/2774 CELEX=02019R0815 success length=2313911
[EURLEX TEXT] 155/2774 processed | success=119 | failed=36
[EURLEX TEXT] 156/2774 CELEX=02019R0815 success length=2337691
[EURLEX TEXT] 157/2774 CELEX=02020A0612(01) failed reason=404_not_found length=0
[EURLEX TEXT] 158/2774 CELEX=02020R0429 success length=2074626
[EURLEX TEXT] 159/2774 CELEX=02020R1208 success length=243379
[EURLEX TEXT] 160/2774 CELEX=02021D0820 success length=121779
[EURLEX TEXT] 160/2774 processed | success=123 | failed=37
[EURLEX TEXT] 161/2774 CELEX=02021R0451 success length=2468114
[EURLEX TEXT] 162/2774 CELEX=02021R0451 success length=2468266
[EURLEX TEXT] 163/2774 CELEX=02021R0451 success length=2549690
[EURLEX TEXT] 164/2774 CELEX=02021R0451 success length=2663599
[EURLEX TEXT] 165/2774 CELEX=02021R0523 success length=167225
[EURLEX TEXT] 165/2774 processed | success=128 | failed=37
[EURLEX TEXT] 166/2774 CELEX=02021R0523 success length=155249
[EURLEX TEXT] 167/2774 CELEX=02021R0523 success length=155365
[EURLEX TEXT] 168/2774 CELEX=02021R0523 success length=170492
[EURLEX TEXT] 169/2774 CELEX=02021R0637 success length=811623
[EURLEX TEXT] 170/2774 CELEX=02021R0947 success length=233033
[EURLEX TEXT] 170/2774 processed | success=133 | failed=37
[EURLEX TEXT] 171/2774 CELEX=02021R1078 success length=199781
[EURLEX TEXT] 172/2774 CELEX=02021R2106 success length=24200
[EURLEX TEXT] 173/2774 CELEX=02021R2115 success length=445494
[EURLEX TEXT] 174/2774 CELEX=02021R2115 success length=386462
[EURLEX TEXT] 175/2774 CELEX=02021R2115 success length=386621
[EURLEX TEXT] 175/2774 processed | success=138 | failed=37
[EURLEX TEXT] 176/2774 CELEX=02021R2115 success length=386733
[EURLEX TEXT] 177/2774 CELEX=02021R2115 success length=388731
[EURLEX TEXT] 178/2774 CELEX=02021R2115 success length=402139
[EURLEX TEXT] 179/2774 CELEX=02021R2115 success length=410341
[EURLEX TEXT] 180/2774 CELEX=02021R2117 success length=126041
[EURLEX TEXT] 180/2774 processed | success=143 | failed=37
[EURLEX TEXT] 181/2774 CELEX=02021R2139 success length=1245569
[EURLEX TEXT] 182/2774 CELEX=02021R2139 success length=1384120
[EURLEX TEXT] 183/2774 CELEX=02021R2139 success length=1384803
[EURLEX TEXT] 184/2774 CELEX=02021R2139 success length=1384900
[EURLEX TEXT] 185/2774 CELEX=02021R2139 success length=1382591
[EURLEX TEXT] 185/2774 processed | success=148 | failed=37
[EURLEX TEXT] 186/2774 CELEX=02021R2178 success length=122682
[EURLEX TEXT] 187/2774 CELEX=02021R2178 success length=120270
[EURLEX TEXT] 188/2774 CELEX=02021R2178 success length=150272
[EURLEX TEXT] 189/2774 CELEX=02021R2178 success length=155989
[EURLEX TEXT] 190/2774 CELEX=02021R2268 success length=114389
[EURLEX TEXT] 190/2774 processed | success=153 | failed=37
[EURLEX TEXT] 191/2774 CELEX=02021R2268 success length=114758
[EURLEX TEXT] 192/2774 CELEX=02021R2289 success length=70687
[EURLEX TEXT] 193/2774 CELEX=02021R2289 success length=69721
[EURLEX TEXT] 194/2774 CELEX=02021R2289 success length=70662
[EURLEX TEXT] 195/2774 CELEX=02022L2523 success length=177819
[EURLEX TEXT] 195/2774 processed | success=158 | failed=37
[EURLEX TEXT] 196/2774 CELEX=02022R0079 success length=17895
[EURLEX TEXT] 197/2774 CELEX=02022R0869 success length=201631
[EURLEX TEXT] 198/2774 CELEX=02022R0869 success length=203954
[EURLEX TEXT] 199/2774 CELEX=02022R1475 success length=79311
[EURLEX TEXT] 200/2774 CELEX=02022R1475 success length=78317
[EURLEX TEXT] 200/2774 processed | success=163 | failed=37
[EURLEX TEXT] cache saved -> eurlex_cache_fulltext.csv
[EURLEX TEXT] 200/2774 processed | success=163 | failed=37
[EURLEX TEXT] 201/2774 CELEX=02022R1475 success length=78919
[EURLEX TEXT] 202/2774 CELEX=02022R2473 success length=192877
[EURLEX TEXT] 203/2774 CELEX=02022R2473 success length=174463
[EURLEX TEXT] 204/2774 CELEX=02022R2473 success length=175023
[EURLEX TEXT] 205/2774 CELEX=02022XC1221(01) failed reason=404_not_found length=0
[EURLEX TEXT] 205/2774 processed | success=167 | failed=38
[EURLEX TEXT] 206/2774 CELEX=02023R1115 success length=103378
[EURLEX TEXT] 207/2774 CELEX=02023R1115 success length=111082
[EURLEX TEXT] 208/2774 CELEX=02023R1803 success length=3223544
[EURLEX TEXT] 209/2774 CELEX=02023R1803 success length=3235047
[EURLEX TEXT] 210/2774 CELEX=02023R1803 success length=3251898
[EURLEX TEXT] 210/2774 processed | success=172 | failed=38
[EURLEX TEXT] 211/2774 CELEX=02023R1803 success length=3277592
[EURLEX TEXT] 212/2774 CELEX=02023R1803 success length=3279848
[EURLEX TEXT] 213/2774 CELEX=02023R2486 success length=504345
[EURLEX TEXT] 214/2774 CELEX=02023R2486 success length=449949
[EURLEX TEXT] 215/2774 CELEX=02023R2772 success length=903275
[EURLEX TEXT] 215/2774 processed | success=177 | failed=38
[EURLEX TEXT] 216/2774 CELEX=02023R2772 success length=910010
[EURLEX TEXT] 217/2774 CELEX=02024R1252 success length=174648
[EURLEX TEXT] 218/2774 CELEX=02024R1735 success length=138593
[EURLEX TEXT] 219/2774 CELEX=02024R1735 success length=153116
[EURLEX TEXT] 220/2774 CELEX=02024R1991 success length=169554
[EURLEX TEXT] 220/2774 processed | success=182 | failed=38
[EURLEX TEXT] 221/2774 CELEX=02024R3012 success length=59380
[EURLEX TEXT] 222/2774 CELEX=21978A0428(01) failed reason=404_not_found length=0
[EURLEX TEXT] 223/2774 CELEX=21995A0805(01) failed reason=404_not_found length=0
[EURLEX TEXT] 224/2774 CELEX=21996A0312(01) failed reason=404_not_found length=0
[EURLEX TEXT] 225/2774 CELEX=21997A1212(03) failed reason=404_not_found length=0
[EURLEX TEXT] 225/2774 processed | success=183 | failed=42
[EURLEX TEXT] 226/2774 CELEX=22003P0926(21) failed reason=404_not_found length=0
[EURLEX TEXT] 227/2774 CELEX=22003P0926(24) failed reason=404_not_found length=0
[EURLEX TEXT] 228/2774 CELEX=22011A1004(01) failed reason=404_not_found length=0
[EURLEX TEXT] 229/2774 CELEX=22014A0520(02) failed reason=404_not_found length=0
[EURLEX TEXT] 230/2774 CELEX=22014A0830(01) failed reason=404_not_found length=0
[EURLEX TEXT] 230/2774 processed | success=183 | failed=47
[EURLEX TEXT] 231/2774 CELEX=22014A0830(02) failed reason=404_not_found length=0
[EURLEX TEXT] 232/2774 CELEX=22015D1382 success length=138064
[EURLEX TEXT] 233/2774 CELEX=22018A0126(01) failed reason=404_not_found length=0
[EURLEX TEXT] 234/2774 CELEX=22020A0612(01) failed reason=404_not_found length=0
[EURLEX TEXT] 235/2774 CELEX=22021P0908(02) failed reason=404_not_found length=0
[EURLEX TEXT] 235/2774 processed | success=184 | failed=51
[EURLEX TEXT] 236/2774 CELEX=22023A02862 success length=490120
[EURLEX TEXT] 237/2774 CELEX=22023A02862R(03) failed reason=404_not_found length=0
[EURLEX TEXT] 238/2774 CELEX=22024A01759 success length=2176686
[EURLEX TEXT] 239/2774 CELEX=22024A02953 success length=1968187
[EURLEX TEXT] 240/2774 CELEX=22024D1537 success length=4148
[EURLEX TEXT] 240/2774 processed | success=188 | failed=52
[EURLEX TEXT] 241/2774 CELEX=22026A00184 success length=4079655
[EURLEX TEXT] 242/2774 CELEX=22026A00186 success length=4186602
[EURLEX TEXT] 243/2774 CELEX=31993D0337 failed reason=404_not_found length=0
[EURLEX TEXT] 244/2774 CELEX=31994D0911 failed reason=404_not_found length=0
[EURLEX TEXT] 245/2774 CELEX=31996L0061 success length=54671
[EURLEX TEXT] 245/2774 processed | success=191 | failed=54
[EURLEX TEXT] 246/2774 CELEX=31999D0152 failed reason=404_not_found length=0
[EURLEX TEXT] 247/2774 CELEX=31999D0182 failed reason=404_not_found length=0
[EURLEX TEXT] 248/2774 CELEX=31999Y0226(01) failed reason=404_not_found length=0
[EURLEX TEXT] 249/2774 CELEX=32000B0081 failed reason=404_not_found length=0

,celex,celex_full,celex_version,title,url,text_source_url,full_text_raw,full_text_clean,text_len,retrieval_status,retrieval_error,lang,lang_source_fulltext,fetch_seconds,fetched_from_cache,text_path,celex_variant_used,route_used,content_type,attempt_trace,celex_valid,celex_sector,celex_sector_label,celex_descriptor,celex_descriptor_label,celex_notes,celex_is_corrigendum,celex_is_consolidated,celex_class,fulltext_support,failure_category
0,01995A0805(01),01995A0805(01)-20131213,20131213,"Convenzione sulla protezione e l’utilizzazione dei corsi d’acqua transfrontalieri e dei laghi internazionali in data, a Helsinki, il 17 marzo 1992 Nazioni unite 1992 Convenzione sulla protezione e l’utilizzazione dei...",https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01995A0805(01)-20131213,http://publications.europa.eu/resource/celex/01995A0805(01),,,0,404,HTTP 404,en,english_fallback,0.04,False,,01995A0805(01),cellar,,"[{'celex_full': '01995A0805(01)-20131213', 'celex': '01995A0805(01)', 'celex_variant': '01995A0805(01)-20131213', 'lang': 'en', 'route_name': 'cellar', 'final_url': 'http://publications.europa.eu/resource/celex/01995...",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported,404_not_found
1,01996A0312(01),01996A0312(01)-20130925,20130925,Convention sur la protection des Alpes (convention alpine),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996A0312(01)-20130925,http://publications.europa.eu/resource/celex/01996A0312(01),,,0,404,HTTP 404,en,english_fallback,0.04,False,,01996A0312(01),cellar,,"[{'celex_full': '01996A0312(01)-20130925', 'celex': '01996A0312(01)', 'celex_variant': '01996A0312(01)-20130925', 'lang': 'en', 'route_name': 'cellar', 'final_url': 'http://publications.europa.eu/resource/celex/01996...",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported,404_not_found
2,02002D0011(01),02002D0011(01)-20051118,20051118,Décision de la Banque centrale européenne du 5 décembre 2002 concernant les comptes annuels de la Banque centrale européenne (BCE/2002/11) (2003/132/CE),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20051118,http://publications.europa.eu/resource/celex/02002D0011(01),,,0,404,HTTP 404,en,english_fallback,0.04,False,,02002D0011(01),cellar,,"[{'celex_full': '02002D0011(01)-20051118', 'celex': '02002D0011(01)', 'celex_variant': '02002D0011(01)-20051118', 'lang': 'en', 'route_name': 'cellar', 'final_url': 'http://publications.europa.eu/resource/celex/02002...",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported,404_not_found
3,02002D0011(01),02002D0011(01)-20060313,20060313,Décision de la Banque centrale européenne du 5 décembre 2002 concernant les comptes annuels de la Banque centrale européenne (BCE/2002/11) (2003/132/CE),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20060313,http://publications.europa.eu/resource/celex/02002D0011(01),,,0,404,HTTP 404,en,english_fallback,0.04,False,,02002D0011(01),cellar,,"[{'celex_full': '02002D0011(01)-20060313', 'celex': '02002D0011(01)', 'celex_variant': '02002D0011(01)-20060313', 'lang': 'en', 'route_name': 'cellar', 'final_url': 'http://publications.europa.eu/resource/celex/02002...",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported,404_not_found
4,02002O0010,02002O0010-20030101,20030101,Orientación del Banco Central Europeo de 5 de diciembre de 2002 sobre el régimen jurídico de la contabilidad y la elaboración de informes financieros en el sistema europeo de Bancos Centrales (BCE/2002/10) (2003/131/CE),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002O0010-20030101,http://publications.europa.eu/resource/celex/02002O0010,,,0,404,HTTP 404,en,english_fallback,0.04,False,,02002O0010,cellar,,"[{'celex_full': '02002O0010-20030101', 'celex': '02002O0010', 'celex_variant': '02002O0010-20030101', 'lang': 'en', 'route_name': 'cellar', 'final_url': 'http://publications.europa.eu/resource/celex/02002O0010-200301...",True,0,Consolidated texts,O,Order / Oral question,,False,True,sector_0_consolidated,supported,sector0_route_mismatch

## Build EU full-text dataframe

In [18]:
use_fallback = fulltext_live_df.empty or not fulltext_live_df["text_len"].gt(0).any()

if use_fallback and ALLOW_FALLBACK:
    print("Using cached full-text fallback from persisted EU full-text export.")
    eu_fulltext_df = load_eu_fulltext_docs(CANONICAL_ALL_DOCS)
elif use_fallback:
    raise RuntimeError("Live full-text retrieval produced no usable texts and fallback is disabled.")
else:
    eu_fulltext_df = fulltext_live_df.copy()
    if FALLBACK_FILL_MISSING_TEXT and ALLOW_FALLBACK and eu_fulltext_df["text_len"].fillna(0).eq(0).any():
        cached_fulltext_df = load_eu_fulltext_docs(CANONICAL_ALL_DOCS)[["celex_full", "full_text_clean", "text_len"]].drop_duplicates(subset=["celex_full"])
        eu_fulltext_df = eu_fulltext_df.merge(cached_fulltext_df, on="celex_full", how="left", suffixes=("", "_cached"))
        fill_mask = eu_fulltext_df["text_len"].fillna(0).eq(0) & eu_fulltext_df["text_len_cached"].fillna(0).gt(0)
        eu_fulltext_df.loc[fill_mask, "full_text_clean"] = eu_fulltext_df.loc[fill_mask, "full_text_clean_cached"]
        eu_fulltext_df.loc[fill_mask, "text_len"] = eu_fulltext_df.loc[fill_mask, "text_len_cached"]
        eu_fulltext_df.loc[fill_mask, "retrieval_error"] = eu_fulltext_df.loc[fill_mask, "retrieval_error"].fillna("") + " | filled_from_cached_export"
        eu_fulltext_df = eu_fulltext_df.drop(columns=[col for col in ["full_text_clean_cached", "text_len_cached"] if col in eu_fulltext_df.columns])

preview_df("eu_fulltext_df", eu_fulltext_df)
display(
    pd.DataFrame(
        [
            {"metric": "EU full-text rows", "value": len(eu_fulltext_df)},
            {"metric": "Rows with non-empty text", "value": int(eu_fulltext_df["text_len"].fillna(0).gt(0).sum())},
            {"metric": "Rows with empty text", "value": int(eu_fulltext_df["text_len"].fillna(0).eq(0).sum())},
        ]
    )
)

eu_fulltext_df: shape=(2774, 31)

,celex,celex_full,celex_version,title,url,text_source_url,full_text_raw,full_text_clean,text_len,retrieval_status,retrieval_error,lang,lang_source_fulltext,fetch_seconds,fetched_from_cache,text_path,celex_variant_used,route_used,content_type,attempt_trace,celex_valid,celex_sector,celex_sector_label,celex_descriptor,celex_descriptor_label,celex_notes,celex_is_corrigendum,celex_is_consolidated,celex_class,fulltext_support,failure_category
0,01995A0805(01),01995A0805(01)-20131213,20131213,"Convenzione sulla protezione e l’utilizzazione dei corsi d’acqua transfrontalieri e dei laghi internazionali in data, a Helsinki, il 17 marzo 1992 Nazioni unite 1992 Convenzione sulla protezione e l’utilizzazione dei...",https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01995A0805(01)-20131213,http://publications.europa.eu/resource/celex/01995A0805(01),,,0,404,HTTP 404,en,english_fallback,0.04,False,,01995A0805(01),cellar,,"[{'celex_full': '01995A0805(01)-20131213', 'celex': '01995A0805(01)', 'celex_variant': '01995A0805(01)-20131213', 'lang': 'en', 'route_name': 'cellar', 'final_url': 'http://publications.europa.eu/resource/celex/01995...",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported,404_not_found
1,01996A0312(01),01996A0312(01)-20130925,20130925,Convention sur la protection des Alpes (convention alpine),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996A0312(01)-20130925,http://publications.europa.eu/resource/celex/01996A0312(01),,,0,404,HTTP 404,en,english_fallback,0.04,False,,01996A0312(01),cellar,,"[{'celex_full': '01996A0312(01)-20130925', 'celex': '01996A0312(01)', 'celex_variant': '01996A0312(01)-20130925', 'lang': 'en', 'route_name': 'cellar', 'final_url': 'http://publications.europa.eu/resource/celex/01996...",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported,404_not_found
2,02002D0011(01),02002D0011(01)-20051118,20051118,Décision de la Banque centrale européenne du 5 décembre 2002 concernant les comptes annuels de la Banque centrale européenne (BCE/2002/11) (2003/132/CE),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20051118,http://publications.europa.eu/resource/celex/02002D0011(01),,,0,404,HTTP 404,en,english_fallback,0.04,False,,02002D0011(01),cellar,,"[{'celex_full': '02002D0011(01)-20051118', 'celex': '02002D0011(01)', 'celex_variant': '02002D0011(01)-20051118', 'lang': 'en', 'route_name': 'cellar', 'final_url': 'http://publications.europa.eu/resource/celex/02002...",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported,404_not_found
3,02002D0011(01),02002D0011(01)-20060313,20060313,Décision de la Banque centrale européenne du 5 décembre 2002 concernant les comptes annuels de la Banque centrale européenne (BCE/2002/11) (2003/132/CE),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20060313,http://publications.europa.eu/resource/celex/02002D0011(01),,,0,404,HTTP 404,en,english_fallback,0.04,False,,02002D0011(01),cellar,,"[{'celex_full': '02002D0011(01)-20060313', 'celex': '02002D0011(01)', 'celex_variant': '02002D0011(01)-20060313', 'lang': 'en', 'route_name': 'cellar', 'final_url': 'http://publications.europa.eu/resource/celex/02002...",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported,404_not_found
4,02002O0010,02002O0010-20030101,20030101,Orientación del Banco Central Europeo de 5 de diciembre de 2002 sobre el régimen jurídico de la contabilidad y la elaboración de informes financieros en el sistema europeo de Bancos Centrales (BCE/2002/10) (2003/131/CE),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002O0010-20030101,http://publications.europa.eu/resource/celex/02002O0010,,,0,404,HTTP 404,en,english_fallback,0.04,False,,02002O0010,cellar,,"[{'celex_full': '02002O0010-20030101', 'celex': '02002O0010', 'celex_variant': '02002O0010-20030101', 'lang': 'en', 'route_name': 'cellar', 'final_url': 'http://publications.europa.eu/resource/celex/02002O0010-200301...",True,0,Consolidated texts,O,Order / Oral question,,False,True,sector_0_consolidated,supported,sector0_route_mismatch

                     metric  value
0         EU full-text rows   2774
1  Rows with non-empty text   1678
2      Rows with empty text   1096

## Save EU retrieval outputs

In [21]:
write_csv(eu_fulltext_df, OUT_FULLTEXT)

Wrote: c:\Users\acali\OneDrive - Danmarks Tekniske Universitet\PostDoc\Code\NiD-Policy-Analysis\analysis_pipeline\outputs\01A_eu_all_fulltext_docs_new.csv
Shape: (2774, 31)

,celex,celex_full,celex_version,title,url,text_source_url,full_text_raw,full_text_clean,text_len,retrieval_status,retrieval_error,lang,lang_source_fulltext,fetch_seconds,fetched_from_cache,text_path,celex_variant_used,route_used,content_type,attempt_trace,celex_valid,celex_sector,celex_sector_label,celex_descriptor,celex_descriptor_label,celex_notes,celex_is_corrigendum,celex_is_consolidated,celex_class,fulltext_support,failure_category
0,01995A0805(01),01995A0805(01)-20131213,20131213,"Convenzione sulla protezione e l’utilizzazione dei corsi d’acqua transfrontalieri e dei laghi internazionali in data, a Helsinki, il 17 marzo 1992 Nazioni unite 1992 Convenzione sulla protezione e l’utilizzazione dei...",https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01995A0805(01)-20131213,http://publications.europa.eu/resource/celex/01995A0805(01),,,0,404,HTTP 404,en,english_fallback,0.04,False,,01995A0805(01),cellar,,"[{'celex_full': '01995A0805(01)-20131213', 'celex': '01995A0805(01)', 'celex_variant': '01995A0805(01)-20131213', 'lang': 'en', 'route_name': 'cellar', 'final_url': 'http://publications.europa.eu/resource/celex/01995...",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported,404_not_found
1,01996A0312(01),01996A0312(01)-20130925,20130925,Convention sur la protection des Alpes (convention alpine),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:01996A0312(01)-20130925,http://publications.europa.eu/resource/celex/01996A0312(01),,,0,404,HTTP 404,en,english_fallback,0.04,False,,01996A0312(01),cellar,,"[{'celex_full': '01996A0312(01)-20130925', 'celex': '01996A0312(01)', 'celex_variant': '01996A0312(01)-20130925', 'lang': 'en', 'route_name': 'cellar', 'final_url': 'http://publications.europa.eu/resource/celex/01996...",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported,404_not_found
2,02002D0011(01),02002D0011(01)-20051118,20051118,Décision de la Banque centrale européenne du 5 décembre 2002 concernant les comptes annuels de la Banque centrale européenne (BCE/2002/11) (2003/132/CE),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20051118,http://publications.europa.eu/resource/celex/02002D0011(01),,,0,404,HTTP 404,en,english_fallback,0.04,False,,02002D0011(01),cellar,,"[{'celex_full': '02002D0011(01)-20051118', 'celex': '02002D0011(01)', 'celex_variant': '02002D0011(01)-20051118', 'lang': 'en', 'route_name': 'cellar', 'final_url': 'http://publications.europa.eu/resource/celex/02002...",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported,404_not_found
3,02002D0011(01),02002D0011(01)-20060313,20060313,Décision de la Banque centrale européenne du 5 décembre 2002 concernant les comptes annuels de la Banque centrale européenne (BCE/2002/11) (2003/132/CE),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002D0011(01)-20060313,http://publications.europa.eu/resource/celex/02002D0011(01),,,0,404,HTTP 404,en,english_fallback,0.04,False,,02002D0011(01),cellar,,"[{'celex_full': '02002D0011(01)-20060313', 'celex': '02002D0011(01)', 'celex_variant': '02002D0011(01)-20060313', 'lang': 'en', 'route_name': 'cellar', 'final_url': 'http://publications.europa.eu/resource/celex/02002...",False,,,,,Pattern mismatch,False,False,unknown_or_invalid,supported,404_not_found
4,02002O0010,02002O0010-20030101,20030101,Orientación del Banco Central Europeo de 5 de diciembre de 2002 sobre el régimen jurídico de la contabilidad y la elaboración de informes financieros en el sistema europeo de Bancos Centrales (BCE/2002/10) (2003/131/CE),https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02002O0010-20030101,http://publications.europa.eu/resource/celex/02002O0010,,,0,404,HTTP 404,en,english_fallback,0.04,False,,02002O0010,cellar,,"[{'celex_full': '02002O0010-20030101', 'celex': '02002O0010', 'celex_variant': '02002O0010-20030101', 'lang': 'en', 'route_name': 'cellar', 'final_url': 'http://publications.europa.eu/resource/celex/02002O0010-200301...",True,0,Consolidated texts,O,Order / Oral question,,False,True,sector_0_consolidated,supported,sector0_route_mismatch