In [1]:
from policy_corpus_builder.adapters.non_eu import (
    fetch_uk_documents,
    run_non_eu_query_pipeline,
)

In [1]:
from policy_corpus_builder.adapters.non_eu import run_non_eu_query_pipeline

run = run_non_eu_query_pipeline(
    "biodiversity",
    countries=("UK",),
    max_per_term=5,
    max_workers=2,
    progress_every=1,
    obey_robots=True,
)

cols = [c for c in [
    "title", "url", "full_text_url", "full_text_error",
    "full_text_format", "retrieval_status", "text_len", "has_text"
] if c in run.fulltext_docs_df.columns]

print(run.fulltext_docs_df[cols])

if "full_text_error" in run.fulltext_docs_df.columns:
    print("\nfull_text_error counts:")
    print(run.fulltext_docs_df["full_text_error"].fillna("<NA>").value_counts(dropna=False))

if "retrieval_status" in run.fulltext_docs_df.columns:
    print("\nretrieval_status counts:")
    print(run.fulltext_docs_df["retrieval_status"].fillna("<NA>").value_counts(dropna=False))

[PROGRESS] 1/3 | ok=0 | errors=1
[PROGRESS] 2/3 | ok=0 | errors=2
[PROGRESS] 3/3 | ok=0 | errors=3
[ERROR SUMMARY]
3x waf_challenge
                                               title  \
0  Natural Environment and Rural Communities Act ...
1                               Environment Act 2021
2  Biodiversity Beyond National Jurisdiction Act ...

                                            url full_text_url full_text_error  \
0  https://www.legislation.gov.uk/ukpga/2006/16                 waf_challenge
1  https://www.legislation.gov.uk/ukpga/2021/30                 waf_challenge
2   https://www.legislation.gov.uk/ukpga/2026/6                 waf_challenge

  full_text_format  retrieval_status  text_len  has_text
0                   upstream_blocked         0     False
1                   upstream_blocked         0     False
2                   upstream_blocked         0     False

full_text_error counts:
full_text_error
waf_challenge    3
Name: count, dtype: int64

retrieval_status counts:
retrieval_status
upstream_blocked    3
Name: count, dtype: int64

In [2]:
path = Path("examples/outputs/non-eu-uk-example/documents.jsonl")

In [3]:
from pathlib import Path
Path.cwd()

WindowsPath('c:/Users/acali/OneDrive - Danmarks Tekniske Universitet/PostDoc/Code/policy-corpus-builder/examples/notebooks')

In [4]:
import json
from pathlib import Path

repo_root = Path.cwd()
if repo_root.name == "notebooks":
    repo_root = repo_root.parent.parent

path = repo_root / "examples" / "outputs" / "non-eu-uk-example" / "documents.jsonl"
print(path)
print(path.exists())

rows = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]

print("records:", len(rows))
print("with full_text:", sum(bool(r.get("full_text")) for r in rows))
print("without full_text:", sum(not bool(r.get("full_text")) for r in rows))

for r in rows[:5]:
    print({
        "title": r.get("title"),
        "url": r.get("url"),
        "has_full_text": bool(r.get("full_text")),
    })

c:\Users\acali\OneDrive - Danmarks Tekniske Universitet\PostDoc\Code\policy-corpus-builder\examples\outputs\non-eu-uk-example\documents.jsonl
True
records: 9
with full_text: 0
without full_text: 9
{'title': 'Natural Environment and Rural Communities Act 2006', 'url': 'https://www.legislation.gov.uk/ukpga/2006/16', 'has_full_text': False}
{'title': 'Environment Act 2021', 'url': 'https://www.legislation.gov.uk/ukpga/2021/30', 'has_full_text': False}
{'title': 'Biodiversity Beyond National Jurisdiction Act 2026', 'url': 'https://www.legislation.gov.uk/ukpga/2026/6', 'has_full_text': False}
{'title': 'Nature Conservation (Scotland) Act 2004', 'url': 'https://www.legislation.gov.uk/asp/2004/6', 'has_full_text': False}
{'title': 'Natural Environment (Scotland) Act 2026 - Explanatory Notes', 'url': 'https://www.legislation.gov.uk/asp/2026/6', 'has_full_text': False}

In [1]:
import json
from pathlib import Path

path = Path("examples/outputs/non-eu-uk-example/documents.jsonl")
rows = [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]

print("records:", len(rows))
print("with full_text:", sum(bool(r.get("full_text")) for r in rows))
print("without full_text:", sum(not bool(r.get("full_text")) for r in rows))

for r in rows[:5]:
    print({
        "title": r.get("title"),
        "url": r.get("url"),
        "has_full_text": bool(r.get("full_text")),
    })

FileNotFoundError: [Errno 2] No such file or directory: 'examples\\outputs\\non-eu-uk-example\\documents.jsonl'

In [2]:
from policy_corpus_builder.adapters.non_eu import fetch_uk_documents

df = fetch_uk_documents(
    ["biodiversity"],
    max_per_term=10,
)

print(df.shape)
df.head()

(5, 13)

,jurisdiction,source,matched_term,term,doc_url,url,title,lang,doc_id,doc_uid,country,year,date
0,United Kingdom,UK,biodiversity,biodiversity,https://www.legislation.gov.uk/ukpga/2021/30/c...,https://www.legislation.gov.uk/ukpga/2021/30/c...,Environment Act 2021 - Legislation.gov.uk,en,ukpga_2021_30,https://www.legislation.gov.uk/ukpga/2021/30/c...,United Kingdom,2021,2021
1,United Kingdom,UK,biodiversity,biodiversity,https://www.legislation.gov.uk/uksi/2024/50/co...,https://www.legislation.gov.uk/uksi/2024/50/co...,The Biodiversity Gain (Town and Country Planni...,en,uksi_2024_50,https://www.legislation.gov.uk/uksi/2024/50/co...,United Kingdom,2024,2024
2,United Kingdom,UK,biodiversity,biodiversity,https://www.legislation.gov.uk/uksi/2024/48/co...,https://www.legislation.gov.uk/uksi/2024/48/co...,The Biodiversity Gain Requirements (Irreplacea...,en,uksi_2024_48,https://www.legislation.gov.uk/uksi/2024/48/co...,United Kingdom,2024,2024
3,United Kingdom,UK,biodiversity,biodiversity,https://www.legislation.gov.uk/ukdsi/2022/9780...,https://www.legislation.gov.uk/ukdsi/2022/9780...,The Environmental Targets (Biodiversity) (Engl...,en,ukdsi_2022_9780348242966,https://www.legislation.gov.uk/ukdsi/2022/9780...,United Kingdom,2022,2022
4,United Kingdom,UK,biodiversity,biodiversity,https://www.legislation.gov.uk/ukpga/2026/6/co...,https://www.legislation.gov.uk/ukpga/2026/6/co...,Biodiversity Beyond National Jurisdiction Act ...,en,ukpga_2026_6,https://www.legislation.gov.uk/ukpga/2026/6/co...,United Kingdom,2026,2026

In [8]:
from policy_corpus_builder.adapters.non_eu import run_non_eu_query_pipeline

run = run_non_eu_query_pipeline(
    ["nature restoration", "nature inclusive", "nature-based solutions"],
    countries=("UK",),
    max_per_term=500,
    max_workers=2,
    progress_every=1,
    obey_robots=True,
)

print("raw hits:", run.raw_hits_df.shape)
print("fulltext docs:", run.fulltext_docs_df.shape)
print("harmonized docs:", run.harmonized_docs_df.shape)

run.raw_hits_df.head()
run.fulltext_docs_df.head()
run.harmonized_docs_df.head()

raw hits: (0, 15)
fulltext docs: (0, 18)
harmonized docs: (0, 18)

Empty DataFrame
Columns: [doc_id, country, jurisdiction, doc_uid, title, url, lang, date, year, source_file, full_text_clean, text_len, has_text, retrieval_status, full_text_url, full_text_error, full_text_format, source]
Index: []